/*
 * Interface wrapper code.
 *
 * Generated by SIP 4.16.6-snapshot-3c5425fa3c80 on Thu Jan 22 20:52:28 2015
 *
 * Copyright (c) 2014 Riverbank Computing Limited <info@riverbankcomputing.com>
 * 
 * This file is part of PyQt5.
 * 
 * This file may be used under the terms of the GNU General Public License
 * version 3.0 as published by the Free Software Foundation and appearing in
 * the file LICENSE included in the packaging of this file.  Please review the
 * following information to ensure the GNU General Public License version 3.0
 * requirements will be met: http://www.gnu.org/copyleft/gpl.html.
 * 
 * If you do not wish to use this file under the terms of the GPL version 3.0
 * then you may purchase a commercial license.  For more information contact
 * info@riverbankcomputing.com.
 * 
 * This file is provided AS IS with NO WARRANTY OF ANY KIND, INCLUDING THE
 * WARRANTY OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 */

#include "sipAPIQtGui.h"

#line 28 "/home/supermap/OpenThings/PyQt-gpl-5.4/sip/QtGui/qpaintdevicewindow.sip"
#include <qpaintdevicewindow.h>
#line 29 "/home/supermap/OpenThings/PyQt-gpl-5.4/QtGui/sipQtGuiQPaintDeviceWindow.cpp"

#line 26 "sip/QtCore/qcoreevent.sip"
#include <qcoreevent.h>
#line 33 "/home/supermap/OpenThings/PyQt-gpl-5.4/QtGui/sipQtGuiQPaintDeviceWindow.cpp"
#line 743 "/home/supermap/OpenThings/PyQt-gpl-5.4/sip/QtGui/qevent.sip"
#include <qevent.h>
#line 36 "/home/supermap/OpenThings/PyQt-gpl-5.4/QtGui/sipQtGuiQPaintDeviceWindow.cpp"
#line 26 "/home/supermap/OpenThings/PyQt-gpl-5.4/sip/QtGui/qpaintdevice.sip"
#include <qpaintdevice.h>
#line 39 "/home/supermap/OpenThings/PyQt-gpl-5.4/QtGui/sipQtGuiQPaintDeviceWindow.cpp"
#line 368 "/home/supermap/OpenThings/PyQt-gpl-5.4/sip/QtGui/qevent.sip"
#include <qevent.h>
#line 42 "/home/supermap/OpenThings/PyQt-gpl-5.4/QtGui/sipQtGuiQPaintDeviceWindow.cpp"
#line 30 "sip/QtCore/qrect.sip"
#include <qrect.h>
#line 45 "/home/supermap/OpenThings/PyQt-gpl-5.4/QtGui/sipQtGuiQPaintDeviceWindow.cpp"
#line 30 "/home/supermap/OpenThings/PyQt-gpl-5.4/sip/QtGui/qregion.sip"
#include <qregion.h>
#line 48 "/home/supermap/OpenThings/PyQt-gpl-5.4/QtGui/sipQtGuiQPaintDeviceWindow.cpp"
#line 26 "/home/supermap/OpenThings/PyQt-gpl-5.4/sip/QtGui/qwindow.sip"
#include <qwindow.h>
#line 51 "/home/supermap/OpenThings/PyQt-gpl-5.4/QtGui/sipQtGuiQPaintDeviceWindow.cpp"
#line 192 "sip/QtCore/qglobal.sip"
#include <QtGlobal>
#line 54 "/home/supermap/OpenThings/PyQt-gpl-5.4/QtGui/sipQtGuiQPaintDeviceWindow.cpp"
#line 275 "/home/supermap/OpenThings/PyQt-gpl-5.4/sip/QtGui/qevent.sip"
#include <qevent.h>
#line 57 "/home/supermap/OpenThings/PyQt-gpl-5.4/QtGui/sipQtGuiQPaintDeviceWindow.cpp"
#line 686 "/home/supermap/OpenThings/PyQt-gpl-5.4/sip/QtGui/qevent.sip"
#include <qevent.h>
#line 60 "/home/supermap/OpenThings/PyQt-gpl-5.4/QtGui/sipQtGuiQPaintDeviceWindow.cpp"
#line 247 "/home/supermap/OpenThings/PyQt-gpl-5.4/sip/QtGui/qevent.sip"
#include <qevent.h>
#line 63 "/home/supermap/OpenThings/PyQt-gpl-5.4/QtGui/sipQtGuiQPaintDeviceWindow.cpp"
#line 202 "/home/supermap/OpenThings/PyQt-gpl-5.4/sip/QtGui/qevent.sip"
#include <qevent.h>
#line 66 "/home/supermap/OpenThings/PyQt-gpl-5.4/QtGui/sipQtGuiQPaintDeviceWindow.cpp"
#line 333 "/home/supermap/OpenThings/PyQt-gpl-5.4/sip/QtGui/qevent.sip"
#include <qevent.h>
#line 69 "/home/supermap/OpenThings/PyQt-gpl-5.4/QtGui/sipQtGuiQPaintDeviceWindow.cpp"
#line 441 "/home/supermap/OpenThings/PyQt-gpl-5.4/sip/QtGui/qevent.sip"
#include <qevent.h>
#line 72 "/home/supermap/OpenThings/PyQt-gpl-5.4/QtGui/sipQtGuiQPaintDeviceWindow.cpp"
#line 430 "/home/supermap/OpenThings/PyQt-gpl-5.4/sip/QtGui/qevent.sip"
#include <qevent.h>
#line 75 "/home/supermap/OpenThings/PyQt-gpl-5.4/QtGui/sipQtGuiQPaintDeviceWindow.cpp"
#line 354 "/home/supermap/OpenThings/PyQt-gpl-5.4/sip/QtGui/qevent.sip"
#include <qevent.h>
#line 78 "/home/supermap/OpenThings/PyQt-gpl-5.4/QtGui/sipQtGuiQPaintDeviceWindow.cpp"
#line 382 "/home/supermap/OpenThings/PyQt-gpl-5.4/sip/QtGui/qevent.sip"
#include <qevent.h>
#line 81 "/home/supermap/OpenThings/PyQt-gpl-5.4/QtGui/sipQtGuiQPaintDeviceWindow.cpp"
#line 395 "/home/supermap/OpenThings/PyQt-gpl-5.4/sip/QtGui/qevent.sip"
#include <qevent.h>
#line 84 "/home/supermap/OpenThings/PyQt-gpl-5.4/QtGui/sipQtGuiQPaintDeviceWindow.cpp"
#line 27 "sip/QtCore/qstring.sip"
#include <qstring.h>
#line 87 "/home/supermap/OpenThings/PyQt-gpl-5.4/QtGui/sipQtGuiQPaintDeviceWindow.cpp"
#line 28 "sip/QtCore/qobject.sip"
#include <qobject.h>
#line 90 "/home/supermap/OpenThings/PyQt-gpl-5.4/QtGui/sipQtGuiQPaintDeviceWindow.cpp"
#line 30 "sip/QtCore/qnamespace.sip"
#include <qnamespace.h>
#line 93 "/home/supermap/OpenThings/PyQt-gpl-5.4/QtGui/sipQtGuiQPaintDeviceWindow.cpp"
#line 26 "/home/supermap/OpenThings/PyQt-gpl-5.4/sip/QtGui/qscreen.sip"
#include <qscreen.h>
#line 96 "/home/supermap/OpenThings/PyQt-gpl-5.4/QtGui/sipQtGuiQPaintDeviceWindow.cpp"
#line 30 "/home/supermap/OpenThings/PyQt-gpl-5.4/sip/QtGui/qcursor.sip"
#include <qcursor.h>
#line 99 "/home/supermap/OpenThings/PyQt-gpl-5.4/QtGui/sipQtGuiQPaintDeviceWindow.cpp"
#line 30 "sip/QtCore/qpoint.sip"
#include <qpoint.h>
#line 102 "/home/supermap/OpenThings/PyQt-gpl-5.4/QtGui/sipQtGuiQPaintDeviceWindow.cpp"
#line 30 "/home/supermap/OpenThings/PyQt-gpl-5.4/sip/QtGui/qicon.sip"
#include <qicon.h>
#line 105 "/home/supermap/OpenThings/PyQt-gpl-5.4/QtGui/sipQtGuiQPaintDeviceWindow.cpp"
#line 30 "sip/QtCore/qsize.sip"
#include <qsize.h>
#line 108 "/home/supermap/OpenThings/PyQt-gpl-5.4/QtGui/sipQtGuiQPaintDeviceWindow.cpp"
#line 30 "sip/QtCore/qmargins.sip"
#include <qmargins.h>
#line 111 "/home/supermap/OpenThings/PyQt-gpl-5.4/QtGui/sipQtGuiQPaintDeviceWindow.cpp"
#line 30 "sip/QtCore/qnamespace.sip"
#include <qnamespace.h>
#line 114 "/home/supermap/OpenThings/PyQt-gpl-5.4/QtGui/sipQtGuiQPaintDeviceWindow.cpp"
#line 30 "/home/supermap/OpenThings/PyQt-gpl-5.4/sip/QtGui/qsurfaceformat.sip"
#include <qsurfaceformat.h>
#line 117 "/home/supermap/OpenThings/PyQt-gpl-5.4/QtGui/sipQtGuiQPaintDeviceWindow.cpp"
#line 26 "/home/supermap/OpenThings/PyQt-gpl-5.4/sip/QtGui/qsurface.sip"
#include <qsurface.h>
#line 120 "/home/supermap/OpenThings/PyQt-gpl-5.4/QtGui/sipQtGuiQPaintDeviceWindow.cpp"
#line 30 "sip/QtCore/qmetaobject.sip"
#include <qmetaobject.h>
#line 123 "/home/supermap/OpenThings/PyQt-gpl-5.4/QtGui/sipQtGuiQPaintDeviceWindow.cpp"
#line 234 "sip/QtCore/qcoreevent.sip"
#include <qcoreevent.h>
#line 126 "/home/supermap/OpenThings/PyQt-gpl-5.4/QtGui/sipQtGuiQPaintDeviceWindow.cpp"
#line 222 "sip/QtCore/qcoreevent.sip"
#include <qcoreevent.h>
#line 129 "/home/supermap/OpenThings/PyQt-gpl-5.4/QtGui/sipQtGuiQPaintDeviceWindow.cpp"
#line 30 "sip/QtCore/qvariant.sip"
#include <qvariant.h>
#line 132 "/home/supermap/OpenThings/PyQt-gpl-5.4/QtGui/sipQtGuiQPaintDeviceWindow.cpp"
#line 36 "sip/QtCore/qpycore_qlist.sip"
#include <qlist.h>
#line 135 "/home/supermap/OpenThings/PyQt-gpl-5.4/QtGui/sipQtGuiQPaintDeviceWindow.cpp"
#line 32 "sip/QtCore/qbytearray.sip"
#include <qbytearray.h>
#line 138 "/home/supermap/OpenThings/PyQt-gpl-5.4/QtGui/sipQtGuiQPaintDeviceWindow.cpp"
#line 144 "sip/QtCore/qpycore_qlist.sip"
#include <qlist.h>
#line 141 "/home/supermap/OpenThings/PyQt-gpl-5.4/QtGui/sipQtGuiQPaintDeviceWindow.cpp"
#line 26 "sip/QtCore/qthread.sip"
#include <qthread.h>
#line 144 "/home/supermap/OpenThings/PyQt-gpl-5.4/QtGui/sipQtGuiQPaintDeviceWindow.cpp"
#line 30 "sip/QtCore/qnamespace.sip"
#include <qnamespace.h>
#line 147 "/home/supermap/OpenThings/PyQt-gpl-5.4/QtGui/sipQtGuiQPaintDeviceWindow.cpp"
#line 30 "sip/QtCore/qregexp.sip"
#include <qregexp.h>
#line 150 "/home/supermap/OpenThings/PyQt-gpl-5.4/QtGui/sipQtGuiQPaintDeviceWindow.cpp"
#line 30 "sip/QtCore/qregularexpression.sip"
#include <qregularexpression.h>
#line 153 "/home/supermap/OpenThings/PyQt-gpl-5.4/QtGui/sipQtGuiQPaintDeviceWindow.cpp"
#line 26 "sip/QtCore/qobjectdefs.sip"
#include <qobjectdefs.h>
#line 156 "/home/supermap/OpenThings/PyQt-gpl-5.4/QtGui/sipQtGuiQPaintDeviceWindow.cpp"
#line 56 "/home/supermap/OpenThings/PyQt-gpl-5.4/sip/QtGui/qpaintengine.sip"
#include <qpaintengine.h>
#line 159 "/home/supermap/OpenThings/PyQt-gpl-5.4/QtGui/sipQtGuiQPaintDeviceWindow.cpp"


PyDoc_STRVAR(doc_QPaintDeviceWindow_update, "QPaintDeviceWindow.update(QRect)\n"
    "QPaintDeviceWindow.update(QRegion)\n"
    "QPaintDeviceWindow.update()");

extern "C" {static PyObject *meth_QPaintDeviceWindow_update(PyObject *, PyObject *);}
static PyObject *meth_QPaintDeviceWindow_update(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const QRect* a0;
        QPaintDeviceWindow *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ9", &sipSelf, sipType_QPaintDeviceWindow, &sipCpp, sipType_QRect, &a0))
        {
            sipCpp->update(*a0);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    {
        const QRegion* a0;
        QPaintDeviceWindow *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ9", &sipSelf, sipType_QPaintDeviceWindow, &sipCpp, sipType_QRegion, &a0))
        {
            sipCpp->update(*a0);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    {
        QPaintDeviceWindow *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QPaintDeviceWindow, &sipCpp))
        {
            sipCpp->update();

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QPaintDeviceWindow, sipName_update, doc_QPaintDeviceWindow_update);

    return NULL;
}


PyDoc_STRVAR(doc_QPaintDeviceWindow_paintEvent, "QPaintDeviceWindow.paintEvent(QPaintEvent)");

extern "C" {static PyObject *meth_QPaintDeviceWindow_paintEvent(PyObject *, PyObject *);}
static PyObject *meth_QPaintDeviceWindow_paintEvent(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        QPaintEvent* a0;
        QPaintDeviceWindow *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "pJ8", &sipSelf, sipType_QPaintDeviceWindow, &sipCpp, sipType_QPaintEvent, &a0))
        {
            (sipSelfWasArg ? sipCpp->QPaintDeviceWindow::paintEvent(a0) : sipCpp->paintEvent(a0));

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QPaintDeviceWindow, sipName_paintEvent, doc_QPaintDeviceWindow_paintEvent);

    return NULL;
}


PyDoc_STRVAR(doc_QPaintDeviceWindow_metric, "QPaintDeviceWindow.metric(QPaintDevice.PaintDeviceMetric) -> int");

extern "C" {static PyObject *meth_QPaintDeviceWindow_metric(PyObject *, PyObject *);}
static PyObject *meth_QPaintDeviceWindow_metric(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        QPaintDevice::PaintDeviceMetric a0;
        const QPaintDeviceWindow *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "pE", &sipSelf, sipType_QPaintDeviceWindow, &sipCpp, sipType_QPaintDevice_PaintDeviceMetric, &a0))
        {
            int sipRes;

            sipRes = (sipSelfWasArg ? sipCpp->QPaintDeviceWindow::metric(a0) : sipCpp->metric(a0));

            return SIPLong_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QPaintDeviceWindow, sipName_metric, doc_QPaintDeviceWindow_metric);

    return NULL;
}


PyDoc_STRVAR(doc_QPaintDeviceWindow_exposeEvent, "QPaintDeviceWindow.exposeEvent(QExposeEvent)");

extern "C" {static PyObject *meth_QPaintDeviceWindow_exposeEvent(PyObject *, PyObject *);}
static PyObject *meth_QPaintDeviceWindow_exposeEvent(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        QExposeEvent* a0;
        QPaintDeviceWindow *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "pJ8", &sipSelf, sipType_QPaintDeviceWindow, &sipCpp, sipType_QExposeEvent, &a0))
        {
            (sipSelfWasArg ? sipCpp->QPaintDeviceWindow::exposeEvent(a0) : sipCpp->exposeEvent(a0));

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QPaintDeviceWindow, sipName_exposeEvent, doc_QPaintDeviceWindow_exposeEvent);

    return NULL;
}


PyDoc_STRVAR(doc_QPaintDeviceWindow_event, "QPaintDeviceWindow.event(QEvent) -> bool");

extern "C" {static PyObject *meth_QPaintDeviceWindow_event(PyObject *, PyObject *);}
static PyObject *meth_QPaintDeviceWindow_event(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        QEvent* a0;
        QPaintDeviceWindow *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "pJ8", &sipSelf, sipType_QPaintDeviceWindow, &sipCpp, sipType_QEvent, &a0))
        {
            bool sipRes;

            sipRes = (sipSelfWasArg ? sipCpp->QPaintDeviceWindow::event(a0) : sipCpp->event(a0));

            return PyBool_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QPaintDeviceWindow, sipName_event, doc_QPaintDeviceWindow_event);

    return NULL;
}


/* Cast a pointer to a type somewhere in its superclass hierarchy. */
extern "C" {static void *cast_QPaintDeviceWindow(void *, const sipTypeDef *);}
static void *cast_QPaintDeviceWindow(void *ptr, const sipTypeDef *targetType)
{
    void *res;

    if (targetType == sipType_QPaintDeviceWindow)
        return ptr;

    if ((res = ((const sipClassTypeDef *)sipType_QWindow)->ctd_cast((QWindow *)(QPaintDeviceWindow *)ptr,targetType)) != NULL)
        return res;

    if ((res = ((const sipClassTypeDef *)sipType_QPaintDevice)->ctd_cast((QPaintDevice *)(QPaintDeviceWindow *)ptr,targetType)) != NULL)
        return res;

    return NULL;
}


/* Call the instance's destructor. */
extern "C" {static void release_QPaintDeviceWindow(void *, int);}
static void release_QPaintDeviceWindow(void *sipCppV,int)
{
    QPaintDeviceWindow *sipCpp = reinterpret_cast<QPaintDeviceWindow *>(sipCppV);

    if (QThread::currentThread() == sipCpp->thread())
        delete sipCpp;
    else
        sipCpp->deleteLater();
}


extern "C" {static void dealloc_QPaintDeviceWindow(sipSimpleWrapper *);}
static void dealloc_QPaintDeviceWindow(sipSimpleWrapper *sipSelf)
{
    if (sipIsPyOwned(sipSelf))
    {
        release_QPaintDeviceWindow(sipGetAddress(sipSelf),0);
    }
}


/* Define this type's super-types. */
static sipEncodedTypeDef supers_QPaintDeviceWindow[] = {{362, 255, 0}, {183, 255, 1}};


static PyMethodDef methods_QPaintDeviceWindow[] = {
    {SIP_MLNAME_CAST(sipName_event), meth_QPaintDeviceWindow_event, METH_VARARGS, SIP_MLDOC_CAST(doc_QPaintDeviceWindow_event)},
    {SIP_MLNAME_CAST(sipName_exposeEvent), meth_QPaintDeviceWindow_exposeEvent, METH_VARARGS, SIP_MLDOC_CAST(doc_QPaintDeviceWindow_exposeEvent)},
    {SIP_MLNAME_CAST(sipName_metric), meth_QPaintDeviceWindow_metric, METH_VARARGS, SIP_MLDOC_CAST(doc_QPaintDeviceWindow_metric)},
    {SIP_MLNAME_CAST(sipName_paintEvent), meth_QPaintDeviceWindow_paintEvent, METH_VARARGS, SIP_MLDOC_CAST(doc_QPaintDeviceWindow_paintEvent)},
    {SIP_MLNAME_CAST(sipName_update), meth_QPaintDeviceWindow_update, METH_VARARGS, SIP_MLDOC_CAST(doc_QPaintDeviceWindow_update)}
};


pyqt5ClassTypeDef sipTypeDef_QtGui_QPaintDeviceWindow = {
{
    {
        -1,
        0,
        0,
        SIP_TYPE_ABSTRACT|SIP_TYPE_SCC|SIP_TYPE_SUPER_INIT|SIP_TYPE_CLASS,
        sipNameNr_QPaintDeviceWindow,
        {0}
    },
    {
        sipNameNr_QPaintDeviceWindow,
        {0, 0, 1},
        5, methods_QPaintDeviceWindow,
        0, 0,
        0, 0,
        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    },
    0,
    -1,
    -1,
    supers_QPaintDeviceWindow,
    0,
    0,
    0,
    0,
#if PY_MAJOR_VERSION >= 3
    0,
    0,
#else
    0,
    0,
    0,
    0,
#endif
    dealloc_QPaintDeviceWindow,
    0,
    0,
    0,
    release_QPaintDeviceWindow,
    cast_QPaintDeviceWindow,
    0,
    0,
    0,
    0,
    0,
    0
},
    &QPaintDeviceWindow::staticMetaObject,
    0,
    0,
    0
};
