/*
 * Interface wrapper code.
 *
 * Generated by SIP 4.16.6-snapshot-3c5425fa3c80 on Thu Jan 22 20:35:28 2015
 *
 * Copyright (c) 2014 Riverbank Computing Limited <info@riverbankcomputing.com>
 * 
 * This file is part of PyQt5.
 * 
 * This file may be used under the terms of the GNU General Public License
 * version 3.0 as published by the Free Software Foundation and appearing in
 * the file LICENSE included in the packaging of this file.  Please review the
 * following information to ensure the GNU General Public License version 3.0
 * requirements will be met: http://www.gnu.org/copyleft/gpl.html.
 * 
 * If you do not wish to use this file under the terms of the GPL version 3.0
 * then you may purchase a commercial license.  For more information contact
 * info@riverbankcomputing.com.
 * 
 * This file is provided AS IS with NO WARRANTY OF ANY KIND, INCLUDING THE
 * WARRANTY OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 */

#include "sipAPIQtWidgets.h"

#line 26 "/home/supermap/OpenThings/pyqt5/sip/QtWidgets/qscrollarea.sip"
#include <qscrollarea.h>
#line 29 "/home/supermap/OpenThings/pyqt5/QtWidgets/sipQtWidgetsQScrollArea.cpp"

#line 30 "/home/supermap/OpenThings/pyqt5/sip/QtWidgets/qwidget.sip"
#include <qwidget.h>
#line 33 "/home/supermap/OpenThings/pyqt5/QtWidgets/sipQtWidgetsQScrollArea.cpp"
#line 30 "sip/QtCore/qsize.sip"
#include <qsize.h>
#line 36 "/home/supermap/OpenThings/pyqt5/QtWidgets/sipQtWidgetsQScrollArea.cpp"
#line 395 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 39 "/home/supermap/OpenThings/pyqt5/QtWidgets/sipQtWidgetsQScrollArea.cpp"
#line 28 "sip/QtCore/qobject.sip"
#include <qobject.h>
#line 42 "/home/supermap/OpenThings/pyqt5/QtWidgets/sipQtWidgetsQScrollArea.cpp"
#line 26 "sip/QtCore/qcoreevent.sip"
#include <qcoreevent.h>
#line 45 "/home/supermap/OpenThings/pyqt5/QtWidgets/sipQtWidgetsQScrollArea.cpp"
#line 30 "sip/QtCore/qnamespace.sip"
#include <qnamespace.h>
#line 48 "/home/supermap/OpenThings/pyqt5/QtWidgets/sipQtWidgetsQScrollArea.cpp"
#line 26 "/home/supermap/OpenThings/pyqt5/sip/QtWidgets/qabstractscrollarea.sip"
#include <qabstractscrollarea.h>
#line 51 "/home/supermap/OpenThings/pyqt5/QtWidgets/sipQtWidgetsQScrollArea.cpp"
#line 144 "sip/QtCore/qpycore_qlist.sip"
#include <qlist.h>
#line 54 "/home/supermap/OpenThings/pyqt5/QtWidgets/sipQtWidgetsQScrollArea.cpp"
#line 26 "/home/supermap/OpenThings/pyqt5/sip/QtWidgets/qscrollbar.sip"
#include <qscrollbar.h>
#line 57 "/home/supermap/OpenThings/pyqt5/QtWidgets/sipQtWidgetsQScrollArea.cpp"
#line 333 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 60 "/home/supermap/OpenThings/pyqt5/QtWidgets/sipQtWidgetsQScrollArea.cpp"
#line 534 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 63 "/home/supermap/OpenThings/pyqt5/QtWidgets/sipQtWidgetsQScrollArea.cpp"
#line 583 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 66 "/home/supermap/OpenThings/pyqt5/QtWidgets/sipQtWidgetsQScrollArea.cpp"
#line 556 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 69 "/home/supermap/OpenThings/pyqt5/QtWidgets/sipQtWidgetsQScrollArea.cpp"
#line 572 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 72 "/home/supermap/OpenThings/pyqt5/QtWidgets/sipQtWidgetsQScrollArea.cpp"
#line 452 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 75 "/home/supermap/OpenThings/pyqt5/QtWidgets/sipQtWidgetsQScrollArea.cpp"
#line 247 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 78 "/home/supermap/OpenThings/pyqt5/QtWidgets/sipQtWidgetsQScrollArea.cpp"
#line 202 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 81 "/home/supermap/OpenThings/pyqt5/QtWidgets/sipQtWidgetsQScrollArea.cpp"
#line 368 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 84 "/home/supermap/OpenThings/pyqt5/QtWidgets/sipQtWidgetsQScrollArea.cpp"
#line 30 "sip/QtCore/qmargins.sip"
#include <qmargins.h>
#line 87 "/home/supermap/OpenThings/pyqt5/QtWidgets/sipQtWidgetsQScrollArea.cpp"
#line 30 "sip/QtCore/qnamespace.sip"
#include <qnamespace.h>
#line 90 "/home/supermap/OpenThings/pyqt5/QtWidgets/sipQtWidgetsQScrollArea.cpp"
#line 30 "sip/QtGui/qpainter.sip"
#include <qpainter.h>
#line 93 "/home/supermap/OpenThings/pyqt5/QtWidgets/sipQtWidgetsQScrollArea.cpp"
#line 30 "sip/QtCore/qrect.sip"
#include <qrect.h>
#line 96 "/home/supermap/OpenThings/pyqt5/QtWidgets/sipQtWidgetsQScrollArea.cpp"
#line 26 "/home/supermap/OpenThings/pyqt5/sip/QtWidgets/qframe.sip"
#include <qframe.h>
#line 99 "/home/supermap/OpenThings/pyqt5/QtWidgets/sipQtWidgetsQScrollArea.cpp"
#line 27 "sip/QtCore/qstring.sip"
#include <qstring.h>
#line 102 "/home/supermap/OpenThings/pyqt5/QtWidgets/sipQtWidgetsQScrollArea.cpp"
#line 30 "sip/QtGui/qicon.sip"
#include <qicon.h>
#line 105 "/home/supermap/OpenThings/pyqt5/QtWidgets/sipQtWidgetsQScrollArea.cpp"
#line 32 "sip/QtCore/qbytearray.sip"
#include <qbytearray.h>
#line 108 "/home/supermap/OpenThings/pyqt5/QtWidgets/sipQtWidgetsQScrollArea.cpp"
#line 26 "sip/QtGui/qwindow.sip"
#include <qwindow.h>
#line 111 "/home/supermap/OpenThings/pyqt5/QtWidgets/sipQtWidgetsQScrollArea.cpp"
#line 30 "sip/QtCore/qnamespace.sip"
#include <qnamespace.h>
#line 114 "/home/supermap/OpenThings/pyqt5/QtWidgets/sipQtWidgetsQScrollArea.cpp"
#line 30 "sip/QtGui/qpixmap.sip"
#include <qpixmap.h>
#line 117 "/home/supermap/OpenThings/pyqt5/QtWidgets/sipQtWidgetsQScrollArea.cpp"
#line 30 "sip/QtCore/qnamespace.sip"
#include <qnamespace.h>
#line 120 "/home/supermap/OpenThings/pyqt5/QtWidgets/sipQtWidgetsQScrollArea.cpp"
#line 30 "sip/QtCore/qnamespace.sip"
#include <qnamespace.h>
#line 123 "/home/supermap/OpenThings/pyqt5/QtWidgets/sipQtWidgetsQScrollArea.cpp"
#line 30 "/home/supermap/OpenThings/pyqt5/sip/QtWidgets/qgraphicseffect.sip"
#include <qgraphicseffect.h>
#line 126 "/home/supermap/OpenThings/pyqt5/QtWidgets/sipQtWidgetsQScrollArea.cpp"
#line 26 "/home/supermap/OpenThings/pyqt5/sip/QtWidgets/qgraphicsproxywidget.sip"
#include <qgraphicsproxywidget.h>
#line 129 "/home/supermap/OpenThings/pyqt5/QtWidgets/sipQtWidgetsQScrollArea.cpp"
#line 192 "sip/QtCore/qglobal.sip"
#include <QtGlobal>
#line 132 "/home/supermap/OpenThings/pyqt5/QtWidgets/sipQtWidgetsQScrollArea.cpp"
#line 30 "sip/QtCore/qlocale.sip"
#include <qlocale.h>
#line 135 "/home/supermap/OpenThings/pyqt5/QtWidgets/sipQtWidgetsQScrollArea.cpp"
#line 26 "sip/QtGui/qpaintdevice.sip"
#include <qpaintdevice.h>
#line 138 "/home/supermap/OpenThings/pyqt5/QtWidgets/sipQtWidgetsQScrollArea.cpp"
#line 30 "sip/QtCore/qpoint.sip"
#include <qpoint.h>
#line 141 "/home/supermap/OpenThings/pyqt5/QtWidgets/sipQtWidgetsQScrollArea.cpp"
#line 30 "sip/QtGui/qregion.sip"
#include <qregion.h>
#line 144 "/home/supermap/OpenThings/pyqt5/QtWidgets/sipQtWidgetsQScrollArea.cpp"
#line 30 "/home/supermap/OpenThings/pyqt5/sip/QtWidgets/qwidget.sip"
#include <qwidget.h>
#line 147 "/home/supermap/OpenThings/pyqt5/QtWidgets/sipQtWidgetsQScrollArea.cpp"
#line 26 "sip/QtGui/qfontinfo.sip"
#include <qfontinfo.h>
#line 150 "/home/supermap/OpenThings/pyqt5/QtWidgets/sipQtWidgetsQScrollArea.cpp"
#line 26 "sip/QtGui/qfontmetrics.sip"
#include <qfontmetrics.h>
#line 153 "/home/supermap/OpenThings/pyqt5/QtWidgets/sipQtWidgetsQScrollArea.cpp"
#line 30 "sip/QtGui/qfont.sip"
#include <qfont.h>
#line 156 "/home/supermap/OpenThings/pyqt5/QtWidgets/sipQtWidgetsQScrollArea.cpp"
#line 30 "sip/QtCore/qvariant.sip"
#include <qvariant.h>
#line 159 "/home/supermap/OpenThings/pyqt5/QtWidgets/sipQtWidgetsQScrollArea.cpp"
#line 479 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 162 "/home/supermap/OpenThings/pyqt5/QtWidgets/sipQtWidgetsQScrollArea.cpp"
#line 441 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 165 "/home/supermap/OpenThings/pyqt5/QtWidgets/sipQtWidgetsQScrollArea.cpp"
#line 430 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 168 "/home/supermap/OpenThings/pyqt5/QtWidgets/sipQtWidgetsQScrollArea.cpp"
#line 635 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 171 "/home/supermap/OpenThings/pyqt5/QtWidgets/sipQtWidgetsQScrollArea.cpp"
#line 275 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 174 "/home/supermap/OpenThings/pyqt5/QtWidgets/sipQtWidgetsQScrollArea.cpp"
#line 408 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 177 "/home/supermap/OpenThings/pyqt5/QtWidgets/sipQtWidgetsQScrollArea.cpp"
#line 382 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 180 "/home/supermap/OpenThings/pyqt5/QtWidgets/sipQtWidgetsQScrollArea.cpp"
#line 354 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 183 "/home/supermap/OpenThings/pyqt5/QtWidgets/sipQtWidgetsQScrollArea.cpp"
#line 56 "sip/QtGui/qpaintengine.sip"
#include <qpaintengine.h>
#line 186 "/home/supermap/OpenThings/pyqt5/QtWidgets/sipQtWidgetsQScrollArea.cpp"
#line 144 "sip/QtCore/qpycore_qlist.sip"
#include <qlist.h>
#line 189 "/home/supermap/OpenThings/pyqt5/QtWidgets/sipQtWidgetsQScrollArea.cpp"
#line 26 "/home/supermap/OpenThings/pyqt5/sip/QtWidgets/qaction.sip"
#include <qaction.h>
#line 192 "/home/supermap/OpenThings/pyqt5/QtWidgets/sipQtWidgetsQScrollArea.cpp"
#line 26 "/home/supermap/OpenThings/pyqt5/sip/QtWidgets/qlayout.sip"
#include <qlayout.h>
#line 195 "/home/supermap/OpenThings/pyqt5/QtWidgets/sipQtWidgetsQScrollArea.cpp"
#line 30 "/home/supermap/OpenThings/pyqt5/sip/QtWidgets/qsizepolicy.sip"
#include <qsizepolicy.h>
#line 198 "/home/supermap/OpenThings/pyqt5/QtWidgets/sipQtWidgetsQScrollArea.cpp"
#line 30 "sip/QtCore/qnamespace.sip"
#include <qnamespace.h>
#line 201 "/home/supermap/OpenThings/pyqt5/QtWidgets/sipQtWidgetsQScrollArea.cpp"
#line 30 "sip/QtGui/qkeysequence.sip"
#include <qkeysequence.h>
#line 204 "/home/supermap/OpenThings/pyqt5/QtWidgets/sipQtWidgetsQScrollArea.cpp"
#line 30 "sip/QtGui/qcursor.sip"
#include <qcursor.h>
#line 207 "/home/supermap/OpenThings/pyqt5/QtWidgets/sipQtWidgetsQScrollArea.cpp"
#line 26 "sip/QtGui/qbitmap.sip"
#include <qbitmap.h>
#line 210 "/home/supermap/OpenThings/pyqt5/QtWidgets/sipQtWidgetsQScrollArea.cpp"
#line 30 "sip/QtGui/qpalette.sip"
#include <qpalette.h>
#line 213 "/home/supermap/OpenThings/pyqt5/QtWidgets/sipQtWidgetsQScrollArea.cpp"
#line 30 "/home/supermap/OpenThings/pyqt5/sip/QtWidgets/qstyle.sip"
#include <qstyle.h>
#line 216 "/home/supermap/OpenThings/pyqt5/QtWidgets/sipQtWidgetsQScrollArea.cpp"
#line 30 "sip/QtCore/qmetaobject.sip"
#include <qmetaobject.h>
#line 219 "/home/supermap/OpenThings/pyqt5/QtWidgets/sipQtWidgetsQScrollArea.cpp"
#line 234 "sip/QtCore/qcoreevent.sip"
#include <qcoreevent.h>
#line 222 "/home/supermap/OpenThings/pyqt5/QtWidgets/sipQtWidgetsQScrollArea.cpp"
#line 222 "sip/QtCore/qcoreevent.sip"
#include <qcoreevent.h>
#line 225 "/home/supermap/OpenThings/pyqt5/QtWidgets/sipQtWidgetsQScrollArea.cpp"
#line 36 "sip/QtCore/qpycore_qlist.sip"
#include <qlist.h>
#line 228 "/home/supermap/OpenThings/pyqt5/QtWidgets/sipQtWidgetsQScrollArea.cpp"
#line 144 "sip/QtCore/qpycore_qlist.sip"
#include <qlist.h>
#line 231 "/home/supermap/OpenThings/pyqt5/QtWidgets/sipQtWidgetsQScrollArea.cpp"
#line 26 "sip/QtCore/qthread.sip"
#include <qthread.h>
#line 234 "/home/supermap/OpenThings/pyqt5/QtWidgets/sipQtWidgetsQScrollArea.cpp"
#line 30 "sip/QtCore/qnamespace.sip"
#include <qnamespace.h>
#line 237 "/home/supermap/OpenThings/pyqt5/QtWidgets/sipQtWidgetsQScrollArea.cpp"
#line 30 "sip/QtCore/qregexp.sip"
#include <qregexp.h>
#line 240 "/home/supermap/OpenThings/pyqt5/QtWidgets/sipQtWidgetsQScrollArea.cpp"
#line 30 "sip/QtCore/qregularexpression.sip"
#include <qregularexpression.h>
#line 243 "/home/supermap/OpenThings/pyqt5/QtWidgets/sipQtWidgetsQScrollArea.cpp"
#line 26 "sip/QtCore/qobjectdefs.sip"
#include <qobjectdefs.h>
#line 246 "/home/supermap/OpenThings/pyqt5/QtWidgets/sipQtWidgetsQScrollArea.cpp"


class sipQScrollArea : public QScrollArea
{
public:
    sipQScrollArea(QWidget*);
    virtual ~sipQScrollArea();

    int qt_metacall(QMetaObject::Call,int,void **);
    void *qt_metacast(const char *);
    const QMetaObject *metaObject() const;

    /*
     * There is a protected method for every virtual method visible from
     * this class.
     */
protected:
    void disconnectNotify(const QMetaMethod&);
    void connectNotify(const QMetaMethod&);
    void customEvent(QEvent*);
    void childEvent(QChildEvent*);
    void timerEvent(QTimerEvent*);
    void initPainter(QPainter*) const;
    QPainter* sharedPainter() const;
    bool nativeEvent(const QByteArray&,void*,long*);
    bool hasHeightForWidth() const;
    QVariant inputMethodQuery(Qt::InputMethodQuery) const;
    void inputMethodEvent(QInputMethodEvent*);
    int metric(QPaintDevice::PaintDeviceMetric) const;
    void hideEvent(QHideEvent*);
    void showEvent(QShowEvent*);
    void actionEvent(QActionEvent*);
    void tabletEvent(QTabletEvent*);
    void closeEvent(QCloseEvent*);
    void moveEvent(QMoveEvent*);
    void leaveEvent(QEvent*);
    void enterEvent(QEvent*);
    void focusOutEvent(QFocusEvent*);
    void focusInEvent(QFocusEvent*);
    void keyReleaseEvent(QKeyEvent*);
    QPaintEngine* paintEngine() const;
    int heightForWidth(int) const;
    void setVisible(bool);
    int devType() const;
    void changeEvent(QEvent*);
    void setupViewport(QWidget*);
    void keyPressEvent(QKeyEvent*);
    void dropEvent(QDropEvent*);
    void dragLeaveEvent(QDragLeaveEvent*);
    void dragMoveEvent(QDragMoveEvent*);
    void dragEnterEvent(QDragEnterEvent*);
    void contextMenuEvent(QContextMenuEvent*);
    void wheelEvent(QWheelEvent*);
    void mouseMoveEvent(QMouseEvent*);
    void mouseDoubleClickEvent(QMouseEvent*);
    void mouseReleaseEvent(QMouseEvent*);
    void mousePressEvent(QMouseEvent*);
    void paintEvent(QPaintEvent*);
    bool viewportEvent(QEvent*);
    QSize minimumSizeHint() const;
    QSize viewportSizeHint() const;
    void scrollContentsBy(int,int);
    void resizeEvent(QResizeEvent*);
    bool eventFilter(QObject*,QEvent*);
    bool event(QEvent*);
    bool focusNextPrevChild(bool);
    QSize sizeHint() const;

public:
    sipSimpleWrapper *sipPySelf;

private:
    sipQScrollArea(const sipQScrollArea &);
    sipQScrollArea &operator = (const sipQScrollArea &);

    char sipPyMethods[50];
};

sipQScrollArea::sipQScrollArea(QWidget*a0): QScrollArea(a0), sipPySelf(0)
{
    memset(sipPyMethods, 0, sizeof (sipPyMethods));
}

sipQScrollArea::~sipQScrollArea()
{
    sipCommonDtor(sipPySelf);
}

const QMetaObject *sipQScrollArea::metaObject() const
{
    return QObject::d_ptr->metaObject ? QObject::d_ptr->dynamicMetaObject() : sip_QtWidgets_qt_metaobject(sipPySelf,sipType_QScrollArea);
}

int sipQScrollArea::qt_metacall(QMetaObject::Call _c,int _id,void **_a)
{
    _id = QScrollArea::qt_metacall(_c,_id,_a);

    if (_id >= 0)
        _id = sip_QtWidgets_qt_metacall(sipPySelf,sipType_QScrollArea,_c,_id,_a);

    return _id;
}

void *sipQScrollArea::qt_metacast(const char *_clname)
{
    void *sipCpp;

    return (sip_QtWidgets_qt_metacast(sipPySelf, sipType_QScrollArea, _clname, &sipCpp) ? sipCpp : QScrollArea::qt_metacast(_clname));
}

void sipQScrollArea::disconnectNotify(const QMetaMethod& a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[0],sipPySelf,NULL,sipName_disconnectNotify);

    if (!sipMeth)
    {
        QScrollArea::disconnectNotify(a0);
        return;
    }

    typedef void (*sipVH_QtCore_46)(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, const QMetaMethod&);

    ((sipVH_QtCore_46)(sipModuleAPI_QtWidgets_QtCore->em_virthandlers[46]))(sipGILState, sipModuleAPI_QtWidgets_QtCore->em_virterrorhandlers[0], sipPySelf, sipMeth, a0);
}

void sipQScrollArea::connectNotify(const QMetaMethod& a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[1],sipPySelf,NULL,sipName_connectNotify);

    if (!sipMeth)
    {
        QScrollArea::connectNotify(a0);
        return;
    }

    typedef void (*sipVH_QtCore_46)(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, const QMetaMethod&);

    ((sipVH_QtCore_46)(sipModuleAPI_QtWidgets_QtCore->em_virthandlers[46]))(sipGILState, sipModuleAPI_QtWidgets_QtCore->em_virterrorhandlers[0], sipPySelf, sipMeth, a0);
}

void sipQScrollArea::customEvent(QEvent*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[2],sipPySelf,NULL,sipName_customEvent);

    if (!sipMeth)
    {
        QScrollArea::customEvent(a0);
        return;
    }

    typedef void (*sipVH_QtCore_25)(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, QEvent*);

    ((sipVH_QtCore_25)(sipModuleAPI_QtWidgets_QtCore->em_virthandlers[25]))(sipGILState, sipModuleAPI_QtWidgets_QtCore->em_virterrorhandlers[0], sipPySelf, sipMeth, a0);
}

void sipQScrollArea::childEvent(QChildEvent*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[3],sipPySelf,NULL,sipName_childEvent);

    if (!sipMeth)
    {
        QScrollArea::childEvent(a0);
        return;
    }

    typedef void (*sipVH_QtCore_47)(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, QChildEvent*);

    ((sipVH_QtCore_47)(sipModuleAPI_QtWidgets_QtCore->em_virthandlers[47]))(sipGILState, sipModuleAPI_QtWidgets_QtCore->em_virterrorhandlers[0], sipPySelf, sipMeth, a0);
}

void sipQScrollArea::timerEvent(QTimerEvent*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[4],sipPySelf,NULL,sipName_timerEvent);

    if (!sipMeth)
    {
        QScrollArea::timerEvent(a0);
        return;
    }

    typedef void (*sipVH_QtCore_9)(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, QTimerEvent*);

    ((sipVH_QtCore_9)(sipModuleAPI_QtWidgets_QtCore->em_virthandlers[9]))(sipGILState, sipModuleAPI_QtWidgets_QtCore->em_virterrorhandlers[0], sipPySelf, sipMeth, a0);
}

void sipQScrollArea::initPainter(QPainter*a0) const
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,const_cast<char *>(&sipPyMethods[5]),sipPySelf,NULL,sipName_initPainter);

    if (!sipMeth)
    {
        QScrollArea::initPainter(a0);
        return;
    }

    extern void sipVH_QtWidgets_3(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, QPainter*);

    sipVH_QtWidgets_3(sipGILState, sipModuleAPI_QtWidgets_QtCore->em_virterrorhandlers[0], sipPySelf, sipMeth, a0);
}

QPainter* sipQScrollArea::sharedPainter() const
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,const_cast<char *>(&sipPyMethods[6]),sipPySelf,NULL,sipName_sharedPainter);

    if (!sipMeth)
        return QScrollArea::sharedPainter();

    extern QPainter* sipVH_QtWidgets_4(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *);

    return sipVH_QtWidgets_4(sipGILState, sipModuleAPI_QtWidgets_QtCore->em_virterrorhandlers[0], sipPySelf, sipMeth);
}

bool sipQScrollArea::nativeEvent(const QByteArray& a0,void*a1,long*a2)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[7],sipPySelf,NULL,sipName_nativeEvent);

    if (!sipMeth)
        return QScrollArea::nativeEvent(a0,a1,a2);

    typedef bool (*sipVH_QtCore_58)(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, const QByteArray&,void*,long*);

    return ((sipVH_QtCore_58)(sipModuleAPI_QtWidgets_QtCore->em_virthandlers[58]))(sipGILState, sipModuleAPI_QtWidgets_QtCore->em_virterrorhandlers[0], sipPySelf, sipMeth, a0, a1, a2);
}

bool sipQScrollArea::hasHeightForWidth() const
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,const_cast<char *>(&sipPyMethods[8]),sipPySelf,NULL,sipName_hasHeightForWidth);

    if (!sipMeth)
        return QScrollArea::hasHeightForWidth();

    typedef bool (*sipVH_QtCore_7)(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *);

    return ((sipVH_QtCore_7)(sipModuleAPI_QtWidgets_QtCore->em_virthandlers[7]))(sipGILState, sipModuleAPI_QtWidgets_QtCore->em_virterrorhandlers[0], sipPySelf, sipMeth);
}

QVariant sipQScrollArea::inputMethodQuery(Qt::InputMethodQuery a0) const
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,const_cast<char *>(&sipPyMethods[9]),sipPySelf,NULL,sipName_inputMethodQuery);

    if (!sipMeth)
        return QScrollArea::inputMethodQuery(a0);

    extern QVariant sipVH_QtWidgets_6(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, Qt::InputMethodQuery);

    return sipVH_QtWidgets_6(sipGILState, sipModuleAPI_QtWidgets_QtCore->em_virterrorhandlers[0], sipPySelf, sipMeth, a0);
}

void sipQScrollArea::inputMethodEvent(QInputMethodEvent*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[10],sipPySelf,NULL,sipName_inputMethodEvent);

    if (!sipMeth)
    {
        QScrollArea::inputMethodEvent(a0);
        return;
    }

    extern void sipVH_QtWidgets_7(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, QInputMethodEvent*);

    sipVH_QtWidgets_7(sipGILState, sipModuleAPI_QtWidgets_QtCore->em_virterrorhandlers[0], sipPySelf, sipMeth, a0);
}

int sipQScrollArea::metric(QPaintDevice::PaintDeviceMetric a0) const
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,const_cast<char *>(&sipPyMethods[11]),sipPySelf,NULL,sipName_metric);

    if (!sipMeth)
        return QScrollArea::metric(a0);

    typedef int (*sipVH_QtGui_28)(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, QPaintDevice::PaintDeviceMetric);

    return ((sipVH_QtGui_28)(sipModuleAPI_QtWidgets_QtGui->em_virthandlers[28]))(sipGILState, sipModuleAPI_QtWidgets_QtCore->em_virterrorhandlers[0], sipPySelf, sipMeth, a0);
}

void sipQScrollArea::hideEvent(QHideEvent*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[12],sipPySelf,NULL,sipName_hideEvent);

    if (!sipMeth)
    {
        QScrollArea::hideEvent(a0);
        return;
    }

    typedef void (*sipVH_QtGui_5)(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, QHideEvent*);

    ((sipVH_QtGui_5)(sipModuleAPI_QtWidgets_QtGui->em_virthandlers[5]))(sipGILState, sipModuleAPI_QtWidgets_QtCore->em_virterrorhandlers[0], sipPySelf, sipMeth, a0);
}

void sipQScrollArea::showEvent(QShowEvent*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[13],sipPySelf,NULL,sipName_showEvent);

    if (!sipMeth)
    {
        QScrollArea::showEvent(a0);
        return;
    }

    typedef void (*sipVH_QtGui_6)(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, QShowEvent*);

    ((sipVH_QtGui_6)(sipModuleAPI_QtWidgets_QtGui->em_virthandlers[6]))(sipGILState, sipModuleAPI_QtWidgets_QtCore->em_virterrorhandlers[0], sipPySelf, sipMeth, a0);
}

void sipQScrollArea::actionEvent(QActionEvent*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[14],sipPySelf,NULL,sipName_actionEvent);

    if (!sipMeth)
    {
        QScrollArea::actionEvent(a0);
        return;
    }

    extern void sipVH_QtWidgets_12(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, QActionEvent*);

    sipVH_QtWidgets_12(sipGILState, sipModuleAPI_QtWidgets_QtCore->em_virterrorhandlers[0], sipPySelf, sipMeth, a0);
}

void sipQScrollArea::tabletEvent(QTabletEvent*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[15],sipPySelf,NULL,sipName_tabletEvent);

    if (!sipMeth)
    {
        QScrollArea::tabletEvent(a0);
        return;
    }

    typedef void (*sipVH_QtGui_0)(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, QTabletEvent*);

    ((sipVH_QtGui_0)(sipModuleAPI_QtWidgets_QtGui->em_virthandlers[0]))(sipGILState, sipModuleAPI_QtWidgets_QtCore->em_virterrorhandlers[0], sipPySelf, sipMeth, a0);
}

void sipQScrollArea::closeEvent(QCloseEvent*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[16],sipPySelf,NULL,sipName_closeEvent);

    if (!sipMeth)
    {
        QScrollArea::closeEvent(a0);
        return;
    }

    extern void sipVH_QtWidgets_14(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, QCloseEvent*);

    sipVH_QtWidgets_14(sipGILState, sipModuleAPI_QtWidgets_QtCore->em_virterrorhandlers[0], sipPySelf, sipMeth, a0);
}

void sipQScrollArea::moveEvent(QMoveEvent*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[17],sipPySelf,NULL,sipName_moveEvent);

    if (!sipMeth)
    {
        QScrollArea::moveEvent(a0);
        return;
    }

    typedef void (*sipVH_QtGui_8)(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, QMoveEvent*);

    ((sipVH_QtGui_8)(sipModuleAPI_QtWidgets_QtGui->em_virthandlers[8]))(sipGILState, sipModuleAPI_QtWidgets_QtCore->em_virterrorhandlers[0], sipPySelf, sipMeth, a0);
}

void sipQScrollArea::leaveEvent(QEvent*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[18],sipPySelf,NULL,sipName_leaveEvent);

    if (!sipMeth)
    {
        QScrollArea::leaveEvent(a0);
        return;
    }

    typedef void (*sipVH_QtCore_25)(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, QEvent*);

    ((sipVH_QtCore_25)(sipModuleAPI_QtWidgets_QtCore->em_virthandlers[25]))(sipGILState, sipModuleAPI_QtWidgets_QtCore->em_virterrorhandlers[0], sipPySelf, sipMeth, a0);
}

void sipQScrollArea::enterEvent(QEvent*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[19],sipPySelf,NULL,sipName_enterEvent);

    if (!sipMeth)
    {
        QScrollArea::enterEvent(a0);
        return;
    }

    typedef void (*sipVH_QtCore_25)(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, QEvent*);

    ((sipVH_QtCore_25)(sipModuleAPI_QtWidgets_QtCore->em_virthandlers[25]))(sipGILState, sipModuleAPI_QtWidgets_QtCore->em_virterrorhandlers[0], sipPySelf, sipMeth, a0);
}

void sipQScrollArea::focusOutEvent(QFocusEvent*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[20],sipPySelf,NULL,sipName_focusOutEvent);

    if (!sipMeth)
    {
        QScrollArea::focusOutEvent(a0);
        return;
    }

    typedef void (*sipVH_QtGui_7)(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, QFocusEvent*);

    ((sipVH_QtGui_7)(sipModuleAPI_QtWidgets_QtGui->em_virthandlers[7]))(sipGILState, sipModuleAPI_QtWidgets_QtCore->em_virterrorhandlers[0], sipPySelf, sipMeth, a0);
}

void sipQScrollArea::focusInEvent(QFocusEvent*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[21],sipPySelf,NULL,sipName_focusInEvent);

    if (!sipMeth)
    {
        QScrollArea::focusInEvent(a0);
        return;
    }

    typedef void (*sipVH_QtGui_7)(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, QFocusEvent*);

    ((sipVH_QtGui_7)(sipModuleAPI_QtWidgets_QtGui->em_virthandlers[7]))(sipGILState, sipModuleAPI_QtWidgets_QtCore->em_virterrorhandlers[0], sipPySelf, sipMeth, a0);
}

void sipQScrollArea::keyReleaseEvent(QKeyEvent*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[22],sipPySelf,NULL,sipName_keyReleaseEvent);

    if (!sipMeth)
    {
        QScrollArea::keyReleaseEvent(a0);
        return;
    }

    typedef void (*sipVH_QtGui_4)(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, QKeyEvent*);

    ((sipVH_QtGui_4)(sipModuleAPI_QtWidgets_QtGui->em_virthandlers[4]))(sipGILState, sipModuleAPI_QtWidgets_QtCore->em_virterrorhandlers[0], sipPySelf, sipMeth, a0);
}

QPaintEngine* sipQScrollArea::paintEngine() const
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,const_cast<char *>(&sipPyMethods[23]),sipPySelf,NULL,sipName_paintEngine);

    if (!sipMeth)
        return QScrollArea::paintEngine();

    typedef QPaintEngine* (*sipVH_QtGui_29)(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *);

    return ((sipVH_QtGui_29)(sipModuleAPI_QtWidgets_QtGui->em_virthandlers[29]))(sipGILState, sipModuleAPI_QtWidgets_QtCore->em_virterrorhandlers[0], sipPySelf, sipMeth);
}

int sipQScrollArea::heightForWidth(int a0) const
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,const_cast<char *>(&sipPyMethods[24]),sipPySelf,NULL,sipName_heightForWidth);

    if (!sipMeth)
        return QScrollArea::heightForWidth(a0);

    typedef int (*sipVH_QtCore_61)(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, int);

    return ((sipVH_QtCore_61)(sipModuleAPI_QtWidgets_QtCore->em_virthandlers[61]))(sipGILState, sipModuleAPI_QtWidgets_QtCore->em_virterrorhandlers[0], sipPySelf, sipMeth, a0);
}

void sipQScrollArea::setVisible(bool a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[25],sipPySelf,NULL,sipName_setVisible);

    if (!sipMeth)
    {
        QScrollArea::setVisible(a0);
        return;
    }

    extern void sipVH_QtWidgets_0(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, bool);

    sipVH_QtWidgets_0(sipGILState, sipModuleAPI_QtWidgets_QtCore->em_virterrorhandlers[0], sipPySelf, sipMeth, a0);
}

int sipQScrollArea::devType() const
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,const_cast<char *>(&sipPyMethods[26]),sipPySelf,NULL,sipName_devType);

    if (!sipMeth)
        return QScrollArea::devType();

    typedef int (*sipVH_QtCore_6)(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *);

    return ((sipVH_QtCore_6)(sipModuleAPI_QtWidgets_QtCore->em_virthandlers[6]))(sipGILState, sipModuleAPI_QtWidgets_QtCore->em_virterrorhandlers[0], sipPySelf, sipMeth);
}

void sipQScrollArea::changeEvent(QEvent*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[27],sipPySelf,NULL,sipName_changeEvent);

    if (!sipMeth)
    {
        QScrollArea::changeEvent(a0);
        return;
    }

    typedef void (*sipVH_QtCore_25)(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, QEvent*);

    ((sipVH_QtCore_25)(sipModuleAPI_QtWidgets_QtCore->em_virthandlers[25]))(sipGILState, sipModuleAPI_QtWidgets_QtCore->em_virterrorhandlers[0], sipPySelf, sipMeth, a0);
}

void sipQScrollArea::setupViewport(QWidget*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[28],sipPySelf,NULL,sipName_setupViewport);

    if (!sipMeth)
    {
        QScrollArea::setupViewport(a0);
        return;
    }

    extern void sipVH_QtWidgets_1(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, QWidget*);

    sipVH_QtWidgets_1(sipGILState, sipModuleAPI_QtWidgets_QtCore->em_virterrorhandlers[0], sipPySelf, sipMeth, a0);
}

void sipQScrollArea::keyPressEvent(QKeyEvent*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[29],sipPySelf,NULL,sipName_keyPressEvent);

    if (!sipMeth)
    {
        QScrollArea::keyPressEvent(a0);
        return;
    }

    typedef void (*sipVH_QtGui_4)(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, QKeyEvent*);

    ((sipVH_QtGui_4)(sipModuleAPI_QtWidgets_QtGui->em_virthandlers[4]))(sipGILState, sipModuleAPI_QtWidgets_QtCore->em_virterrorhandlers[0], sipPySelf, sipMeth, a0);
}

void sipQScrollArea::dropEvent(QDropEvent*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[30],sipPySelf,NULL,sipName_dropEvent);

    if (!sipMeth)
    {
        QScrollArea::dropEvent(a0);
        return;
    }

    extern void sipVH_QtWidgets_8(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, QDropEvent*);

    sipVH_QtWidgets_8(sipGILState, sipModuleAPI_QtWidgets_QtCore->em_virterrorhandlers[0], sipPySelf, sipMeth, a0);
}

void sipQScrollArea::dragLeaveEvent(QDragLeaveEvent*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[31],sipPySelf,NULL,sipName_dragLeaveEvent);

    if (!sipMeth)
    {
        QScrollArea::dragLeaveEvent(a0);
        return;
    }

    extern void sipVH_QtWidgets_9(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, QDragLeaveEvent*);

    sipVH_QtWidgets_9(sipGILState, sipModuleAPI_QtWidgets_QtCore->em_virterrorhandlers[0], sipPySelf, sipMeth, a0);
}

void sipQScrollArea::dragMoveEvent(QDragMoveEvent*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[32],sipPySelf,NULL,sipName_dragMoveEvent);

    if (!sipMeth)
    {
        QScrollArea::dragMoveEvent(a0);
        return;
    }

    extern void sipVH_QtWidgets_10(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, QDragMoveEvent*);

    sipVH_QtWidgets_10(sipGILState, sipModuleAPI_QtWidgets_QtCore->em_virterrorhandlers[0], sipPySelf, sipMeth, a0);
}

void sipQScrollArea::dragEnterEvent(QDragEnterEvent*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[33],sipPySelf,NULL,sipName_dragEnterEvent);

    if (!sipMeth)
    {
        QScrollArea::dragEnterEvent(a0);
        return;
    }

    extern void sipVH_QtWidgets_11(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, QDragEnterEvent*);

    sipVH_QtWidgets_11(sipGILState, sipModuleAPI_QtWidgets_QtCore->em_virterrorhandlers[0], sipPySelf, sipMeth, a0);
}

void sipQScrollArea::contextMenuEvent(QContextMenuEvent*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[34],sipPySelf,NULL,sipName_contextMenuEvent);

    if (!sipMeth)
    {
        QScrollArea::contextMenuEvent(a0);
        return;
    }

    extern void sipVH_QtWidgets_13(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, QContextMenuEvent*);

    sipVH_QtWidgets_13(sipGILState, sipModuleAPI_QtWidgets_QtCore->em_virterrorhandlers[0], sipPySelf, sipMeth, a0);
}

void sipQScrollArea::wheelEvent(QWheelEvent*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[35],sipPySelf,NULL,sipName_wheelEvent);

    if (!sipMeth)
    {
        QScrollArea::wheelEvent(a0);
        return;
    }

    typedef void (*sipVH_QtGui_2)(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, QWheelEvent*);

    ((sipVH_QtGui_2)(sipModuleAPI_QtWidgets_QtGui->em_virthandlers[2]))(sipGILState, sipModuleAPI_QtWidgets_QtCore->em_virterrorhandlers[0], sipPySelf, sipMeth, a0);
}

void sipQScrollArea::mouseMoveEvent(QMouseEvent*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[36],sipPySelf,NULL,sipName_mouseMoveEvent);

    if (!sipMeth)
    {
        QScrollArea::mouseMoveEvent(a0);
        return;
    }

    typedef void (*sipVH_QtGui_3)(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, QMouseEvent*);

    ((sipVH_QtGui_3)(sipModuleAPI_QtWidgets_QtGui->em_virthandlers[3]))(sipGILState, sipModuleAPI_QtWidgets_QtCore->em_virterrorhandlers[0], sipPySelf, sipMeth, a0);
}

void sipQScrollArea::mouseDoubleClickEvent(QMouseEvent*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[37],sipPySelf,NULL,sipName_mouseDoubleClickEvent);

    if (!sipMeth)
    {
        QScrollArea::mouseDoubleClickEvent(a0);
        return;
    }

    typedef void (*sipVH_QtGui_3)(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, QMouseEvent*);

    ((sipVH_QtGui_3)(sipModuleAPI_QtWidgets_QtGui->em_virthandlers[3]))(sipGILState, sipModuleAPI_QtWidgets_QtCore->em_virterrorhandlers[0], sipPySelf, sipMeth, a0);
}

void sipQScrollArea::mouseReleaseEvent(QMouseEvent*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[38],sipPySelf,NULL,sipName_mouseReleaseEvent);

    if (!sipMeth)
    {
        QScrollArea::mouseReleaseEvent(a0);
        return;
    }

    typedef void (*sipVH_QtGui_3)(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, QMouseEvent*);

    ((sipVH_QtGui_3)(sipModuleAPI_QtWidgets_QtGui->em_virthandlers[3]))(sipGILState, sipModuleAPI_QtWidgets_QtCore->em_virterrorhandlers[0], sipPySelf, sipMeth, a0);
}

void sipQScrollArea::mousePressEvent(QMouseEvent*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[39],sipPySelf,NULL,sipName_mousePressEvent);

    if (!sipMeth)
    {
        QScrollArea::mousePressEvent(a0);
        return;
    }

    typedef void (*sipVH_QtGui_3)(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, QMouseEvent*);

    ((sipVH_QtGui_3)(sipModuleAPI_QtWidgets_QtGui->em_virthandlers[3]))(sipGILState, sipModuleAPI_QtWidgets_QtCore->em_virterrorhandlers[0], sipPySelf, sipMeth, a0);
}

void sipQScrollArea::paintEvent(QPaintEvent*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[40],sipPySelf,NULL,sipName_paintEvent);

    if (!sipMeth)
    {
        QScrollArea::paintEvent(a0);
        return;
    }

    typedef void (*sipVH_QtGui_52)(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, QPaintEvent*);

    ((sipVH_QtGui_52)(sipModuleAPI_QtWidgets_QtGui->em_virthandlers[52]))(sipGILState, sipModuleAPI_QtWidgets_QtCore->em_virterrorhandlers[0], sipPySelf, sipMeth, a0);
}

bool sipQScrollArea::viewportEvent(QEvent*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[41],sipPySelf,NULL,sipName_viewportEvent);

    if (!sipMeth)
        return QScrollArea::viewportEvent(a0);

    typedef bool (*sipVH_QtCore_5)(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, QEvent*);

    return ((sipVH_QtCore_5)(sipModuleAPI_QtWidgets_QtCore->em_virthandlers[5]))(sipGILState, sipModuleAPI_QtWidgets_QtCore->em_virterrorhandlers[0], sipPySelf, sipMeth, a0);
}

QSize sipQScrollArea::minimumSizeHint() const
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,const_cast<char *>(&sipPyMethods[42]),sipPySelf,NULL,sipName_minimumSizeHint);

    if (!sipMeth)
        return QScrollArea::minimumSizeHint();

    typedef QSize (*sipVH_QtGui_12)(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *);

    return ((sipVH_QtGui_12)(sipModuleAPI_QtWidgets_QtGui->em_virthandlers[12]))(sipGILState, sipModuleAPI_QtWidgets_QtCore->em_virterrorhandlers[0], sipPySelf, sipMeth);
}

QSize sipQScrollArea::viewportSizeHint() const
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,const_cast<char *>(&sipPyMethods[43]),sipPySelf,NULL,sipName_viewportSizeHint);

    if (!sipMeth)
        return QScrollArea::viewportSizeHint();

    typedef QSize (*sipVH_QtGui_12)(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *);

    return ((sipVH_QtGui_12)(sipModuleAPI_QtWidgets_QtGui->em_virthandlers[12]))(sipGILState, sipModuleAPI_QtWidgets_QtCore->em_virterrorhandlers[0], sipPySelf, sipMeth);
}

void sipQScrollArea::scrollContentsBy(int a0,int a1)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[44],sipPySelf,NULL,sipName_scrollContentsBy);

    if (!sipMeth)
    {
        QScrollArea::scrollContentsBy(a0,a1);
        return;
    }

    typedef void (*sipVH_QtGui_17)(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, int,int);

    ((sipVH_QtGui_17)(sipModuleAPI_QtWidgets_QtGui->em_virthandlers[17]))(sipGILState, sipModuleAPI_QtWidgets_QtCore->em_virterrorhandlers[0], sipPySelf, sipMeth, a0, a1);
}

void sipQScrollArea::resizeEvent(QResizeEvent*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[45],sipPySelf,NULL,sipName_resizeEvent);

    if (!sipMeth)
    {
        QScrollArea::resizeEvent(a0);
        return;
    }

    typedef void (*sipVH_QtGui_9)(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, QResizeEvent*);

    ((sipVH_QtGui_9)(sipModuleAPI_QtWidgets_QtGui->em_virthandlers[9]))(sipGILState, sipModuleAPI_QtWidgets_QtCore->em_virterrorhandlers[0], sipPySelf, sipMeth, a0);
}

bool sipQScrollArea::eventFilter(QObject*a0,QEvent*a1)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[46],sipPySelf,NULL,sipName_eventFilter);

    if (!sipMeth)
        return QScrollArea::eventFilter(a0,a1);

    typedef bool (*sipVH_QtCore_26)(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, QObject*,QEvent*);

    return ((sipVH_QtCore_26)(sipModuleAPI_QtWidgets_QtCore->em_virthandlers[26]))(sipGILState, sipModuleAPI_QtWidgets_QtCore->em_virterrorhandlers[0], sipPySelf, sipMeth, a0, a1);
}

bool sipQScrollArea::event(QEvent*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[47],sipPySelf,NULL,sipName_event);

    if (!sipMeth)
        return QScrollArea::event(a0);

    typedef bool (*sipVH_QtCore_5)(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, QEvent*);

    return ((sipVH_QtCore_5)(sipModuleAPI_QtWidgets_QtCore->em_virthandlers[5]))(sipGILState, sipModuleAPI_QtWidgets_QtCore->em_virterrorhandlers[0], sipPySelf, sipMeth, a0);
}

bool sipQScrollArea::focusNextPrevChild(bool a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[48],sipPySelf,NULL,sipName_focusNextPrevChild);

    if (!sipMeth)
        return QScrollArea::focusNextPrevChild(a0);

    extern bool sipVH_QtWidgets_5(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, bool);

    return sipVH_QtWidgets_5(sipGILState, sipModuleAPI_QtWidgets_QtCore->em_virterrorhandlers[0], sipPySelf, sipMeth, a0);
}

QSize sipQScrollArea::sizeHint() const
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,const_cast<char *>(&sipPyMethods[49]),sipPySelf,NULL,sipName_sizeHint);

    if (!sipMeth)
        return QScrollArea::sizeHint();

    typedef QSize (*sipVH_QtGui_12)(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *);

    return ((sipVH_QtGui_12)(sipModuleAPI_QtWidgets_QtGui->em_virthandlers[12]))(sipGILState, sipModuleAPI_QtWidgets_QtCore->em_virterrorhandlers[0], sipPySelf, sipMeth);
}


PyDoc_STRVAR(doc_QScrollArea_widget, "QScrollArea.widget() -> QWidget");

extern "C" {static PyObject *meth_QScrollArea_widget(PyObject *, PyObject *);}
static PyObject *meth_QScrollArea_widget(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const QScrollArea *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QScrollArea, &sipCpp))
        {
            QWidget*sipRes;

            sipRes = sipCpp->widget();

            return sipConvertFromType(sipRes,sipType_QWidget,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QScrollArea, sipName_widget, doc_QScrollArea_widget);

    return NULL;
}


PyDoc_STRVAR(doc_QScrollArea_setWidget, "QScrollArea.setWidget(QWidget)");

extern "C" {static PyObject *meth_QScrollArea_setWidget(PyObject *, PyObject *);}
static PyObject *meth_QScrollArea_setWidget(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        QWidget* a0;
        QScrollArea *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ:", &sipSelf, sipType_QScrollArea, &sipCpp, sipType_QWidget, &a0))
        {
            sipCpp->setWidget(a0);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QScrollArea, sipName_setWidget, doc_QScrollArea_setWidget);

    return NULL;
}


PyDoc_STRVAR(doc_QScrollArea_takeWidget, "QScrollArea.takeWidget() -> QWidget");

extern "C" {static PyObject *meth_QScrollArea_takeWidget(PyObject *, PyObject *);}
static PyObject *meth_QScrollArea_takeWidget(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        QScrollArea *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QScrollArea, &sipCpp))
        {
            QWidget*sipRes;

            sipRes = sipCpp->takeWidget();

            return sipConvertFromType(sipRes,sipType_QWidget,Py_None);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QScrollArea, sipName_takeWidget, doc_QScrollArea_takeWidget);

    return NULL;
}


PyDoc_STRVAR(doc_QScrollArea_widgetResizable, "QScrollArea.widgetResizable() -> bool");

extern "C" {static PyObject *meth_QScrollArea_widgetResizable(PyObject *, PyObject *);}
static PyObject *meth_QScrollArea_widgetResizable(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const QScrollArea *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QScrollArea, &sipCpp))
        {
            bool sipRes;

            sipRes = sipCpp->widgetResizable();

            return PyBool_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QScrollArea, sipName_widgetResizable, doc_QScrollArea_widgetResizable);

    return NULL;
}


PyDoc_STRVAR(doc_QScrollArea_setWidgetResizable, "QScrollArea.setWidgetResizable(bool)");

extern "C" {static PyObject *meth_QScrollArea_setWidgetResizable(PyObject *, PyObject *);}
static PyObject *meth_QScrollArea_setWidgetResizable(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        bool a0;
        QScrollArea *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bb", &sipSelf, sipType_QScrollArea, &sipCpp, &a0))
        {
            sipCpp->setWidgetResizable(a0);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QScrollArea, sipName_setWidgetResizable, doc_QScrollArea_setWidgetResizable);

    return NULL;
}


PyDoc_STRVAR(doc_QScrollArea_alignment, "QScrollArea.alignment() -> Qt.Alignment");

extern "C" {static PyObject *meth_QScrollArea_alignment(PyObject *, PyObject *);}
static PyObject *meth_QScrollArea_alignment(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const QScrollArea *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QScrollArea, &sipCpp))
        {
            Qt::Alignment*sipRes;

            sipRes = new Qt::Alignment(sipCpp->alignment());

            return sipConvertFromNewType(sipRes,sipType_Qt_Alignment,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QScrollArea, sipName_alignment, doc_QScrollArea_alignment);

    return NULL;
}


PyDoc_STRVAR(doc_QScrollArea_setAlignment, "QScrollArea.setAlignment(Qt.Alignment)");

extern "C" {static PyObject *meth_QScrollArea_setAlignment(PyObject *, PyObject *);}
static PyObject *meth_QScrollArea_setAlignment(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        Qt::Alignment* a0;
        int a0State = 0;
        QScrollArea *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ1", &sipSelf, sipType_QScrollArea, &sipCpp, sipType_Qt_Alignment, &a0, &a0State))
        {
            sipCpp->setAlignment(*a0);
            sipReleaseType(a0,sipType_Qt_Alignment,a0State);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QScrollArea, sipName_setAlignment, doc_QScrollArea_setAlignment);

    return NULL;
}


PyDoc_STRVAR(doc_QScrollArea_sizeHint, "QScrollArea.sizeHint() -> QSize");

extern "C" {static PyObject *meth_QScrollArea_sizeHint(PyObject *, PyObject *);}
static PyObject *meth_QScrollArea_sizeHint(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        const QScrollArea *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QScrollArea, &sipCpp))
        {
            QSize*sipRes;

            sipRes = new QSize((sipSelfWasArg ? sipCpp->QScrollArea::sizeHint() : sipCpp->sizeHint()));

            return sipConvertFromNewType(sipRes,sipType_QSize,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QScrollArea, sipName_sizeHint, doc_QScrollArea_sizeHint);

    return NULL;
}


PyDoc_STRVAR(doc_QScrollArea_focusNextPrevChild, "QScrollArea.focusNextPrevChild(bool) -> bool");

extern "C" {static PyObject *meth_QScrollArea_focusNextPrevChild(PyObject *, PyObject *);}
static PyObject *meth_QScrollArea_focusNextPrevChild(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        bool a0;
        QScrollArea *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bb", &sipSelf, sipType_QScrollArea, &sipCpp, &a0))
        {
            bool sipRes;

            sipRes = (sipSelfWasArg ? sipCpp->QScrollArea::focusNextPrevChild(a0) : sipCpp->focusNextPrevChild(a0));

            return PyBool_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QScrollArea, sipName_focusNextPrevChild, doc_QScrollArea_focusNextPrevChild);

    return NULL;
}


PyDoc_STRVAR(doc_QScrollArea_ensureVisible, "QScrollArea.ensureVisible(int, int, int xMargin=50, int yMargin=50)");

extern "C" {static PyObject *meth_QScrollArea_ensureVisible(PyObject *, PyObject *, PyObject *);}
static PyObject *meth_QScrollArea_ensureVisible(PyObject *sipSelf, PyObject *sipArgs, PyObject *sipKwds)
{
    PyObject *sipParseErr = NULL;

    {
        int a0;
        int a1;
        int a2 = 50;
        int a3 = 50;
        QScrollArea *sipCpp;

        static const char *sipKwdList[] = {
            NULL,
            NULL,
            sipName_xMargin,
            sipName_yMargin,
        };

        if (sipParseKwdArgs(&sipParseErr, sipArgs, sipKwds, sipKwdList, NULL, "Bii|ii", &sipSelf, sipType_QScrollArea, &sipCpp, &a0, &a1, &a2, &a3))
        {
            sipCpp->ensureVisible(a0,a1,a2,a3);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QScrollArea, sipName_ensureVisible, doc_QScrollArea_ensureVisible);

    return NULL;
}


PyDoc_STRVAR(doc_QScrollArea_ensureWidgetVisible, "QScrollArea.ensureWidgetVisible(QWidget, int xMargin=50, int yMargin=50)");

extern "C" {static PyObject *meth_QScrollArea_ensureWidgetVisible(PyObject *, PyObject *, PyObject *);}
static PyObject *meth_QScrollArea_ensureWidgetVisible(PyObject *sipSelf, PyObject *sipArgs, PyObject *sipKwds)
{
    PyObject *sipParseErr = NULL;

    {
        QWidget* a0;
        int a1 = 50;
        int a2 = 50;
        QScrollArea *sipCpp;

        static const char *sipKwdList[] = {
            NULL,
            sipName_xMargin,
            sipName_yMargin,
        };

        if (sipParseKwdArgs(&sipParseErr, sipArgs, sipKwds, sipKwdList, NULL, "BJ8|ii", &sipSelf, sipType_QScrollArea, &sipCpp, sipType_QWidget, &a0, &a1, &a2))
        {
            sipCpp->ensureWidgetVisible(a0,a1,a2);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QScrollArea, sipName_ensureWidgetVisible, doc_QScrollArea_ensureWidgetVisible);

    return NULL;
}


PyDoc_STRVAR(doc_QScrollArea_event, "QScrollArea.event(QEvent) -> bool");

extern "C" {static PyObject *meth_QScrollArea_event(PyObject *, PyObject *);}
static PyObject *meth_QScrollArea_event(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        QEvent* a0;
        QScrollArea *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "pJ8", &sipSelf, sipType_QScrollArea, &sipCpp, sipType_QEvent, &a0))
        {
            bool sipRes;

            sipRes = (sipSelfWasArg ? sipCpp->QScrollArea::event(a0) : sipCpp->event(a0));

            return PyBool_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QScrollArea, sipName_event, doc_QScrollArea_event);

    return NULL;
}


PyDoc_STRVAR(doc_QScrollArea_eventFilter, "QScrollArea.eventFilter(QObject, QEvent) -> bool");

extern "C" {static PyObject *meth_QScrollArea_eventFilter(PyObject *, PyObject *);}
static PyObject *meth_QScrollArea_eventFilter(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        QObject* a0;
        QEvent* a1;
        QScrollArea *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "pJ8J8", &sipSelf, sipType_QScrollArea, &sipCpp, sipType_QObject, &a0, sipType_QEvent, &a1))
        {
            bool sipRes;

            sipRes = (sipSelfWasArg ? sipCpp->QScrollArea::eventFilter(a0,a1) : sipCpp->eventFilter(a0,a1));

            return PyBool_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QScrollArea, sipName_eventFilter, doc_QScrollArea_eventFilter);

    return NULL;
}


PyDoc_STRVAR(doc_QScrollArea_resizeEvent, "QScrollArea.resizeEvent(QResizeEvent)");

extern "C" {static PyObject *meth_QScrollArea_resizeEvent(PyObject *, PyObject *);}
static PyObject *meth_QScrollArea_resizeEvent(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        QResizeEvent* a0;
        QScrollArea *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "pJ8", &sipSelf, sipType_QScrollArea, &sipCpp, sipType_QResizeEvent, &a0))
        {
            (sipSelfWasArg ? sipCpp->QScrollArea::resizeEvent(a0) : sipCpp->resizeEvent(a0));

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QScrollArea, sipName_resizeEvent, doc_QScrollArea_resizeEvent);

    return NULL;
}


PyDoc_STRVAR(doc_QScrollArea_scrollContentsBy, "QScrollArea.scrollContentsBy(int, int)");

extern "C" {static PyObject *meth_QScrollArea_scrollContentsBy(PyObject *, PyObject *);}
static PyObject *meth_QScrollArea_scrollContentsBy(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        int a0;
        int a1;
        QScrollArea *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "pii", &sipSelf, sipType_QScrollArea, &sipCpp, &a0, &a1))
        {
            (sipSelfWasArg ? sipCpp->QScrollArea::scrollContentsBy(a0,a1) : sipCpp->scrollContentsBy(a0,a1));

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QScrollArea, sipName_scrollContentsBy, doc_QScrollArea_scrollContentsBy);

    return NULL;
}


PyDoc_STRVAR(doc_QScrollArea_viewportSizeHint, "QScrollArea.viewportSizeHint() -> QSize");

extern "C" {static PyObject *meth_QScrollArea_viewportSizeHint(PyObject *, PyObject *);}
static PyObject *meth_QScrollArea_viewportSizeHint(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        const QScrollArea *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "p", &sipSelf, sipType_QScrollArea, &sipCpp))
        {
            QSize*sipRes;

            sipRes = new QSize((sipSelfWasArg ? sipCpp->QScrollArea::viewportSizeHint() : sipCpp->viewportSizeHint()));

            return sipConvertFromNewType(sipRes,sipType_QSize,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QScrollArea, sipName_viewportSizeHint, doc_QScrollArea_viewportSizeHint);

    return NULL;
}


/* Cast a pointer to a type somewhere in its superclass hierarchy. */
extern "C" {static void *cast_QScrollArea(void *, const sipTypeDef *);}
static void *cast_QScrollArea(void *ptr, const sipTypeDef *targetType)
{
    void *res;

    if (targetType == sipType_QScrollArea)
        return ptr;

    if ((res = ((const sipClassTypeDef *)sipType_QAbstractScrollArea)->ctd_cast((QAbstractScrollArea *)(QScrollArea *)ptr,targetType)) != NULL)
        return res;

    return NULL;
}


/* Call the instance's destructor. */
extern "C" {static void release_QScrollArea(void *, int);}
static void release_QScrollArea(void *sipCppV,int)
{
    QScrollArea *sipCpp = reinterpret_cast<QScrollArea *>(sipCppV);

    if (QThread::currentThread() == sipCpp->thread())
        delete sipCpp;
    else
        sipCpp->deleteLater();
}


extern "C" {static void dealloc_QScrollArea(sipSimpleWrapper *);}
static void dealloc_QScrollArea(sipSimpleWrapper *sipSelf)
{
    if (sipIsDerived(sipSelf))
        reinterpret_cast<sipQScrollArea *>(sipGetAddress(sipSelf))->sipPySelf = NULL;

    if (sipIsPyOwned(sipSelf))
    {
        release_QScrollArea(sipGetAddress(sipSelf),sipSelf->flags);
    }
}


extern "C" {static void *init_type_QScrollArea(sipSimpleWrapper *, PyObject *, PyObject *, PyObject **, PyObject **, PyObject **);}
static void *init_type_QScrollArea(sipSimpleWrapper *sipSelf, PyObject *sipArgs, PyObject *sipKwds, PyObject **sipUnused, PyObject **sipOwner, PyObject **sipParseErr)
{
    sipQScrollArea *sipCpp = 0;

    {
        QWidget* a0 = 0;

        static const char *sipKwdList[] = {
            sipName_parent,
        };

        if (sipParseKwdArgs(sipParseErr, sipArgs, sipKwds, sipKwdList, sipUnused, "|JH", sipType_QWidget, &a0, sipOwner))
        {
            sipCpp = new sipQScrollArea(a0);

            sipCpp->sipPySelf = sipSelf;

            return sipCpp;
        }
    }

    return NULL;
}


/* Define this type's super-types. */
static sipEncodedTypeDef supers_QScrollArea[] = {{15, 255, 1}};


static PyMethodDef methods_QScrollArea[] = {
    {SIP_MLNAME_CAST(sipName_alignment), meth_QScrollArea_alignment, METH_VARARGS, SIP_MLDOC_CAST(doc_QScrollArea_alignment)},
    {SIP_MLNAME_CAST(sipName_ensureVisible), (PyCFunction)meth_QScrollArea_ensureVisible, METH_VARARGS|METH_KEYWORDS, SIP_MLDOC_CAST(doc_QScrollArea_ensureVisible)},
    {SIP_MLNAME_CAST(sipName_ensureWidgetVisible), (PyCFunction)meth_QScrollArea_ensureWidgetVisible, METH_VARARGS|METH_KEYWORDS, SIP_MLDOC_CAST(doc_QScrollArea_ensureWidgetVisible)},
    {SIP_MLNAME_CAST(sipName_event), meth_QScrollArea_event, METH_VARARGS, SIP_MLDOC_CAST(doc_QScrollArea_event)},
    {SIP_MLNAME_CAST(sipName_eventFilter), meth_QScrollArea_eventFilter, METH_VARARGS, SIP_MLDOC_CAST(doc_QScrollArea_eventFilter)},
    {SIP_MLNAME_CAST(sipName_focusNextPrevChild), meth_QScrollArea_focusNextPrevChild, METH_VARARGS, SIP_MLDOC_CAST(doc_QScrollArea_focusNextPrevChild)},
    {SIP_MLNAME_CAST(sipName_resizeEvent), meth_QScrollArea_resizeEvent, METH_VARARGS, SIP_MLDOC_CAST(doc_QScrollArea_resizeEvent)},
    {SIP_MLNAME_CAST(sipName_scrollContentsBy), meth_QScrollArea_scrollContentsBy, METH_VARARGS, SIP_MLDOC_CAST(doc_QScrollArea_scrollContentsBy)},
    {SIP_MLNAME_CAST(sipName_setAlignment), meth_QScrollArea_setAlignment, METH_VARARGS, SIP_MLDOC_CAST(doc_QScrollArea_setAlignment)},
    {SIP_MLNAME_CAST(sipName_setWidget), meth_QScrollArea_setWidget, METH_VARARGS, SIP_MLDOC_CAST(doc_QScrollArea_setWidget)},
    {SIP_MLNAME_CAST(sipName_setWidgetResizable), meth_QScrollArea_setWidgetResizable, METH_VARARGS, SIP_MLDOC_CAST(doc_QScrollArea_setWidgetResizable)},
    {SIP_MLNAME_CAST(sipName_sizeHint), meth_QScrollArea_sizeHint, METH_VARARGS, SIP_MLDOC_CAST(doc_QScrollArea_sizeHint)},
    {SIP_MLNAME_CAST(sipName_takeWidget), meth_QScrollArea_takeWidget, METH_VARARGS, SIP_MLDOC_CAST(doc_QScrollArea_takeWidget)},
    {SIP_MLNAME_CAST(sipName_viewportSizeHint), meth_QScrollArea_viewportSizeHint, METH_VARARGS, SIP_MLDOC_CAST(doc_QScrollArea_viewportSizeHint)},
    {SIP_MLNAME_CAST(sipName_widget), meth_QScrollArea_widget, METH_VARARGS, SIP_MLDOC_CAST(doc_QScrollArea_widget)},
    {SIP_MLNAME_CAST(sipName_widgetResizable), meth_QScrollArea_widgetResizable, METH_VARARGS, SIP_MLDOC_CAST(doc_QScrollArea_widgetResizable)}
};

PyDoc_STRVAR(doc_QScrollArea, "\1QScrollArea(QWidget parent=None)");


pyqt5ClassTypeDef sipTypeDef_QtWidgets_QScrollArea = {
{
    {
        -1,
        0,
        0,
        SIP_TYPE_SCC|SIP_TYPE_SUPER_INIT|SIP_TYPE_CLASS,
        sipNameNr_QScrollArea,
        {0}
    },
    {
        sipNameNr_QScrollArea,
        {0, 0, 1},
        16, methods_QScrollArea,
        0, 0,
        0, 0,
        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    },
    doc_QScrollArea,
    -1,
    -1,
    supers_QScrollArea,
    0,
    init_type_QScrollArea,
    0,
    0,
#if PY_MAJOR_VERSION >= 3
    0,
    0,
#else
    0,
    0,
    0,
    0,
#endif
    dealloc_QScrollArea,
    0,
    0,
    0,
    release_QScrollArea,
    cast_QScrollArea,
    0,
    0,
    0,
    0,
    0,
    0
},
    &QScrollArea::staticMetaObject,
    0,
    0,
    0
};
