/*
 * Interface wrapper code.
 *
 * Generated by SIP 4.16.6-snapshot-3c5425fa3c80 on Thu Jan 22 20:35:28 2015
 *
 * Copyright (c) 2014 Riverbank Computing Limited <info@riverbankcomputing.com>
 * 
 * This file is part of PyQt5.
 * 
 * This file may be used under the terms of the GNU General Public License
 * version 3.0 as published by the Free Software Foundation and appearing in
 * the file LICENSE included in the packaging of this file.  Please review the
 * following information to ensure the GNU General Public License version 3.0
 * requirements will be met: http://www.gnu.org/copyleft/gpl.html.
 * 
 * If you do not wish to use this file under the terms of the GPL version 3.0
 * then you may purchase a commercial license.  For more information contact
 * info@riverbankcomputing.com.
 * 
 * This file is provided AS IS with NO WARRANTY OF ANY KIND, INCLUDING THE
 * WARRANTY OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 */

#include "sipAPIQtWidgets.h"

#line 26 "/home/supermap/OpenThings/pyqt5/sip/QtWidgets/qwidgetaction.sip"
#include <qwidgetaction.h>
#line 29 "/home/supermap/OpenThings/pyqt5/QtWidgets/sipQtWidgetsQWidgetAction.cpp"

#line 28 "sip/QtCore/qobject.sip"
#include <qobject.h>
#line 33 "/home/supermap/OpenThings/pyqt5/QtWidgets/sipQtWidgetsQWidgetAction.cpp"
#line 144 "sip/QtCore/qpycore_qlist.sip"
#include <qlist.h>
#line 36 "/home/supermap/OpenThings/pyqt5/QtWidgets/sipQtWidgetsQWidgetAction.cpp"
#line 30 "/home/supermap/OpenThings/pyqt5/sip/QtWidgets/qwidget.sip"
#include <qwidget.h>
#line 39 "/home/supermap/OpenThings/pyqt5/QtWidgets/sipQtWidgetsQWidgetAction.cpp"
#line 26 "sip/QtCore/qcoreevent.sip"
#include <qcoreevent.h>
#line 42 "/home/supermap/OpenThings/pyqt5/QtWidgets/sipQtWidgetsQWidgetAction.cpp"
#line 26 "/home/supermap/OpenThings/pyqt5/sip/QtWidgets/qaction.sip"
#include <qaction.h>
#line 45 "/home/supermap/OpenThings/pyqt5/QtWidgets/sipQtWidgetsQWidgetAction.cpp"
#line 144 "sip/QtCore/qpycore_qlist.sip"
#include <qlist.h>
#line 48 "/home/supermap/OpenThings/pyqt5/QtWidgets/sipQtWidgetsQWidgetAction.cpp"
#line 26 "/home/supermap/OpenThings/pyqt5/sip/QtWidgets/qgraphicswidget.sip"
#include <qgraphicswidget.h>
#line 51 "/home/supermap/OpenThings/pyqt5/QtWidgets/sipQtWidgetsQWidgetAction.cpp"
#line 36 "sip/QtCore/qpycore_qlist.sip"
#include <qlist.h>
#line 54 "/home/supermap/OpenThings/pyqt5/QtWidgets/sipQtWidgetsQWidgetAction.cpp"
#line 30 "sip/QtGui/qkeysequence.sip"
#include <qkeysequence.h>
#line 57 "/home/supermap/OpenThings/pyqt5/QtWidgets/sipQtWidgetsQWidgetAction.cpp"
#line 30 "sip/QtCore/qvariant.sip"
#include <qvariant.h>
#line 60 "/home/supermap/OpenThings/pyqt5/QtWidgets/sipQtWidgetsQWidgetAction.cpp"
#line 30 "sip/QtGui/qfont.sip"
#include <qfont.h>
#line 63 "/home/supermap/OpenThings/pyqt5/QtWidgets/sipQtWidgetsQWidgetAction.cpp"
#line 30 "sip/QtCore/qnamespace.sip"
#include <qnamespace.h>
#line 66 "/home/supermap/OpenThings/pyqt5/QtWidgets/sipQtWidgetsQWidgetAction.cpp"
#line 26 "/home/supermap/OpenThings/pyqt5/sip/QtWidgets/qmenu.sip"
#include <qmenu.h>
#line 69 "/home/supermap/OpenThings/pyqt5/QtWidgets/sipQtWidgetsQWidgetAction.cpp"
#line 27 "sip/QtCore/qstring.sip"
#include <qstring.h>
#line 72 "/home/supermap/OpenThings/pyqt5/QtWidgets/sipQtWidgetsQWidgetAction.cpp"
#line 30 "sip/QtGui/qicon.sip"
#include <qicon.h>
#line 75 "/home/supermap/OpenThings/pyqt5/QtWidgets/sipQtWidgetsQWidgetAction.cpp"
#line 26 "/home/supermap/OpenThings/pyqt5/sip/QtWidgets/qactiongroup.sip"
#include <qactiongroup.h>
#line 78 "/home/supermap/OpenThings/pyqt5/QtWidgets/sipQtWidgetsQWidgetAction.cpp"
#line 30 "sip/QtCore/qmetaobject.sip"
#include <qmetaobject.h>
#line 81 "/home/supermap/OpenThings/pyqt5/QtWidgets/sipQtWidgetsQWidgetAction.cpp"
#line 234 "sip/QtCore/qcoreevent.sip"
#include <qcoreevent.h>
#line 84 "/home/supermap/OpenThings/pyqt5/QtWidgets/sipQtWidgetsQWidgetAction.cpp"
#line 222 "sip/QtCore/qcoreevent.sip"
#include <qcoreevent.h>
#line 87 "/home/supermap/OpenThings/pyqt5/QtWidgets/sipQtWidgetsQWidgetAction.cpp"
#line 36 "sip/QtCore/qpycore_qlist.sip"
#include <qlist.h>
#line 90 "/home/supermap/OpenThings/pyqt5/QtWidgets/sipQtWidgetsQWidgetAction.cpp"
#line 32 "sip/QtCore/qbytearray.sip"
#include <qbytearray.h>
#line 93 "/home/supermap/OpenThings/pyqt5/QtWidgets/sipQtWidgetsQWidgetAction.cpp"
#line 144 "sip/QtCore/qpycore_qlist.sip"
#include <qlist.h>
#line 96 "/home/supermap/OpenThings/pyqt5/QtWidgets/sipQtWidgetsQWidgetAction.cpp"
#line 26 "sip/QtCore/qthread.sip"
#include <qthread.h>
#line 99 "/home/supermap/OpenThings/pyqt5/QtWidgets/sipQtWidgetsQWidgetAction.cpp"
#line 30 "sip/QtCore/qnamespace.sip"
#include <qnamespace.h>
#line 102 "/home/supermap/OpenThings/pyqt5/QtWidgets/sipQtWidgetsQWidgetAction.cpp"
#line 30 "sip/QtCore/qregexp.sip"
#include <qregexp.h>
#line 105 "/home/supermap/OpenThings/pyqt5/QtWidgets/sipQtWidgetsQWidgetAction.cpp"
#line 30 "sip/QtCore/qregularexpression.sip"
#include <qregularexpression.h>
#line 108 "/home/supermap/OpenThings/pyqt5/QtWidgets/sipQtWidgetsQWidgetAction.cpp"
#line 26 "sip/QtCore/qobjectdefs.sip"
#include <qobjectdefs.h>
#line 111 "/home/supermap/OpenThings/pyqt5/QtWidgets/sipQtWidgetsQWidgetAction.cpp"


class sipQWidgetAction : public QWidgetAction
{
public:
    sipQWidgetAction(QObject*);
    virtual ~sipQWidgetAction();

    int qt_metacall(QMetaObject::Call,int,void **);
    void *qt_metacast(const char *);
    const QMetaObject *metaObject() const;

    /*
     * There is a protected method for every virtual method visible from
     * this class.
     */
protected:
    void disconnectNotify(const QMetaMethod&);
    void connectNotify(const QMetaMethod&);
    void customEvent(QEvent*);
    void childEvent(QChildEvent*);
    void timerEvent(QTimerEvent*);
    void deleteWidget(QWidget*);
    QWidget* createWidget(QWidget*);
    bool eventFilter(QObject*,QEvent*);
    bool event(QEvent*);

public:
    sipSimpleWrapper *sipPySelf;

private:
    sipQWidgetAction(const sipQWidgetAction &);
    sipQWidgetAction &operator = (const sipQWidgetAction &);

    char sipPyMethods[9];
};

sipQWidgetAction::sipQWidgetAction(QObject*a0): QWidgetAction(a0), sipPySelf(0)
{
    memset(sipPyMethods, 0, sizeof (sipPyMethods));
}

sipQWidgetAction::~sipQWidgetAction()
{
    sipCommonDtor(sipPySelf);
}

const QMetaObject *sipQWidgetAction::metaObject() const
{
    return QObject::d_ptr->metaObject ? QObject::d_ptr->dynamicMetaObject() : sip_QtWidgets_qt_metaobject(sipPySelf,sipType_QWidgetAction);
}

int sipQWidgetAction::qt_metacall(QMetaObject::Call _c,int _id,void **_a)
{
    _id = QWidgetAction::qt_metacall(_c,_id,_a);

    if (_id >= 0)
        _id = sip_QtWidgets_qt_metacall(sipPySelf,sipType_QWidgetAction,_c,_id,_a);

    return _id;
}

void *sipQWidgetAction::qt_metacast(const char *_clname)
{
    void *sipCpp;

    return (sip_QtWidgets_qt_metacast(sipPySelf, sipType_QWidgetAction, _clname, &sipCpp) ? sipCpp : QWidgetAction::qt_metacast(_clname));
}

void sipQWidgetAction::disconnectNotify(const QMetaMethod& a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[0],sipPySelf,NULL,sipName_disconnectNotify);

    if (!sipMeth)
    {
        QWidgetAction::disconnectNotify(a0);
        return;
    }

    typedef void (*sipVH_QtCore_46)(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, const QMetaMethod&);

    ((sipVH_QtCore_46)(sipModuleAPI_QtWidgets_QtCore->em_virthandlers[46]))(sipGILState, sipModuleAPI_QtWidgets_QtCore->em_virterrorhandlers[0], sipPySelf, sipMeth, a0);
}

void sipQWidgetAction::connectNotify(const QMetaMethod& a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[1],sipPySelf,NULL,sipName_connectNotify);

    if (!sipMeth)
    {
        QWidgetAction::connectNotify(a0);
        return;
    }

    typedef void (*sipVH_QtCore_46)(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, const QMetaMethod&);

    ((sipVH_QtCore_46)(sipModuleAPI_QtWidgets_QtCore->em_virthandlers[46]))(sipGILState, sipModuleAPI_QtWidgets_QtCore->em_virterrorhandlers[0], sipPySelf, sipMeth, a0);
}

void sipQWidgetAction::customEvent(QEvent*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[2],sipPySelf,NULL,sipName_customEvent);

    if (!sipMeth)
    {
        QWidgetAction::customEvent(a0);
        return;
    }

    typedef void (*sipVH_QtCore_25)(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, QEvent*);

    ((sipVH_QtCore_25)(sipModuleAPI_QtWidgets_QtCore->em_virthandlers[25]))(sipGILState, sipModuleAPI_QtWidgets_QtCore->em_virterrorhandlers[0], sipPySelf, sipMeth, a0);
}

void sipQWidgetAction::childEvent(QChildEvent*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[3],sipPySelf,NULL,sipName_childEvent);

    if (!sipMeth)
    {
        QWidgetAction::childEvent(a0);
        return;
    }

    typedef void (*sipVH_QtCore_47)(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, QChildEvent*);

    ((sipVH_QtCore_47)(sipModuleAPI_QtWidgets_QtCore->em_virthandlers[47]))(sipGILState, sipModuleAPI_QtWidgets_QtCore->em_virterrorhandlers[0], sipPySelf, sipMeth, a0);
}

void sipQWidgetAction::timerEvent(QTimerEvent*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[4],sipPySelf,NULL,sipName_timerEvent);

    if (!sipMeth)
    {
        QWidgetAction::timerEvent(a0);
        return;
    }

    typedef void (*sipVH_QtCore_9)(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, QTimerEvent*);

    ((sipVH_QtCore_9)(sipModuleAPI_QtWidgets_QtCore->em_virthandlers[9]))(sipGILState, sipModuleAPI_QtWidgets_QtCore->em_virterrorhandlers[0], sipPySelf, sipMeth, a0);
}

void sipQWidgetAction::deleteWidget(QWidget*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[5],sipPySelf,NULL,sipName_deleteWidget);

    if (!sipMeth)
    {
        QWidgetAction::deleteWidget(a0);
        return;
    }

    extern void sipVH_QtWidgets_1(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, QWidget*);

    sipVH_QtWidgets_1(sipGILState, sipModuleAPI_QtWidgets_QtCore->em_virterrorhandlers[0], sipPySelf, sipMeth, a0);
}

QWidget* sipQWidgetAction::createWidget(QWidget*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[6],sipPySelf,NULL,sipName_createWidget);

    if (!sipMeth)
        return QWidgetAction::createWidget(a0);

    extern QWidget* sipVH_QtWidgets_2(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, QWidget*);

    return sipVH_QtWidgets_2(sipGILState, sipModuleAPI_QtWidgets_QtCore->em_virterrorhandlers[0], sipPySelf, sipMeth, a0);
}

bool sipQWidgetAction::eventFilter(QObject*a0,QEvent*a1)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[7],sipPySelf,NULL,sipName_eventFilter);

    if (!sipMeth)
        return QWidgetAction::eventFilter(a0,a1);

    typedef bool (*sipVH_QtCore_26)(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, QObject*,QEvent*);

    return ((sipVH_QtCore_26)(sipModuleAPI_QtWidgets_QtCore->em_virthandlers[26]))(sipGILState, sipModuleAPI_QtWidgets_QtCore->em_virterrorhandlers[0], sipPySelf, sipMeth, a0, a1);
}

bool sipQWidgetAction::event(QEvent*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[8],sipPySelf,NULL,sipName_event);

    if (!sipMeth)
        return QWidgetAction::event(a0);

    typedef bool (*sipVH_QtCore_5)(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, QEvent*);

    return ((sipVH_QtCore_5)(sipModuleAPI_QtWidgets_QtCore->em_virthandlers[5]))(sipGILState, sipModuleAPI_QtWidgets_QtCore->em_virterrorhandlers[0], sipPySelf, sipMeth, a0);
}


PyDoc_STRVAR(doc_QWidgetAction_setDefaultWidget, "QWidgetAction.setDefaultWidget(QWidget)");

extern "C" {static PyObject *meth_QWidgetAction_setDefaultWidget(PyObject *, PyObject *);}
static PyObject *meth_QWidgetAction_setDefaultWidget(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        QWidget* a0;
        QWidgetAction *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ:", &sipSelf, sipType_QWidgetAction, &sipCpp, sipType_QWidget, &a0))
        {
            sipCpp->setDefaultWidget(a0);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QWidgetAction, sipName_setDefaultWidget, doc_QWidgetAction_setDefaultWidget);

    return NULL;
}


PyDoc_STRVAR(doc_QWidgetAction_defaultWidget, "QWidgetAction.defaultWidget() -> QWidget");

extern "C" {static PyObject *meth_QWidgetAction_defaultWidget(PyObject *, PyObject *);}
static PyObject *meth_QWidgetAction_defaultWidget(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const QWidgetAction *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QWidgetAction, &sipCpp))
        {
            QWidget*sipRes;

            sipRes = sipCpp->defaultWidget();

            return sipConvertFromType(sipRes,sipType_QWidget,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QWidgetAction, sipName_defaultWidget, doc_QWidgetAction_defaultWidget);

    return NULL;
}


PyDoc_STRVAR(doc_QWidgetAction_requestWidget, "QWidgetAction.requestWidget(QWidget) -> QWidget");

extern "C" {static PyObject *meth_QWidgetAction_requestWidget(PyObject *, PyObject *);}
static PyObject *meth_QWidgetAction_requestWidget(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        QWidget* a0;
        sipWrapper *sipOwner = 0;
        QWidgetAction *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJH", &sipSelf, sipType_QWidgetAction, &sipCpp, sipType_QWidget, &a0, &sipOwner))
        {
            QWidget*sipRes;

            sipRes = sipCpp->requestWidget(a0);

            return sipConvertFromNewType(sipRes,sipType_QWidget,(PyObject *)sipOwner);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QWidgetAction, sipName_requestWidget, doc_QWidgetAction_requestWidget);

    return NULL;
}


PyDoc_STRVAR(doc_QWidgetAction_releaseWidget, "QWidgetAction.releaseWidget(QWidget)");

extern "C" {static PyObject *meth_QWidgetAction_releaseWidget(PyObject *, PyObject *);}
static PyObject *meth_QWidgetAction_releaseWidget(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        QWidget* a0;
        QWidgetAction *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ<", &sipSelf, sipType_QWidgetAction, &sipCpp, sipType_QWidget, &a0))
        {
            sipCpp->releaseWidget(a0);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QWidgetAction, sipName_releaseWidget, doc_QWidgetAction_releaseWidget);

    return NULL;
}


PyDoc_STRVAR(doc_QWidgetAction_event, "QWidgetAction.event(QEvent) -> bool");

extern "C" {static PyObject *meth_QWidgetAction_event(PyObject *, PyObject *);}
static PyObject *meth_QWidgetAction_event(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        QEvent* a0;
        QWidgetAction *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "pJ8", &sipSelf, sipType_QWidgetAction, &sipCpp, sipType_QEvent, &a0))
        {
            bool sipRes;

            sipRes = (sipSelfWasArg ? sipCpp->QWidgetAction::event(a0) : sipCpp->event(a0));

            return PyBool_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QWidgetAction, sipName_event, doc_QWidgetAction_event);

    return NULL;
}


PyDoc_STRVAR(doc_QWidgetAction_eventFilter, "QWidgetAction.eventFilter(QObject, QEvent) -> bool");

extern "C" {static PyObject *meth_QWidgetAction_eventFilter(PyObject *, PyObject *);}
static PyObject *meth_QWidgetAction_eventFilter(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        QObject* a0;
        QEvent* a1;
        QWidgetAction *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "pJ8J8", &sipSelf, sipType_QWidgetAction, &sipCpp, sipType_QObject, &a0, sipType_QEvent, &a1))
        {
            bool sipRes;

            sipRes = (sipSelfWasArg ? sipCpp->QWidgetAction::eventFilter(a0,a1) : sipCpp->eventFilter(a0,a1));

            return PyBool_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QWidgetAction, sipName_eventFilter, doc_QWidgetAction_eventFilter);

    return NULL;
}


PyDoc_STRVAR(doc_QWidgetAction_createWidget, "QWidgetAction.createWidget(QWidget) -> QWidget");

extern "C" {static PyObject *meth_QWidgetAction_createWidget(PyObject *, PyObject *);}
static PyObject *meth_QWidgetAction_createWidget(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        QWidget* a0;
        sipWrapper *sipOwner = 0;
        QWidgetAction *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "pJH", &sipSelf, sipType_QWidgetAction, &sipCpp, sipType_QWidget, &a0, &sipOwner))
        {
            QWidget*sipRes;

            sipRes = (sipSelfWasArg ? sipCpp->QWidgetAction::createWidget(a0) : sipCpp->createWidget(a0));

            return sipConvertFromNewType(sipRes,sipType_QWidget,(PyObject *)sipOwner);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QWidgetAction, sipName_createWidget, doc_QWidgetAction_createWidget);

    return NULL;
}


PyDoc_STRVAR(doc_QWidgetAction_deleteWidget, "QWidgetAction.deleteWidget(QWidget)");

extern "C" {static PyObject *meth_QWidgetAction_deleteWidget(PyObject *, PyObject *);}
static PyObject *meth_QWidgetAction_deleteWidget(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        QWidget* a0;
        QWidgetAction *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "pJ:", &sipSelf, sipType_QWidgetAction, &sipCpp, sipType_QWidget, &a0))
        {
            (sipSelfWasArg ? sipCpp->QWidgetAction::deleteWidget(a0) : sipCpp->deleteWidget(a0));

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QWidgetAction, sipName_deleteWidget, doc_QWidgetAction_deleteWidget);

    return NULL;
}


PyDoc_STRVAR(doc_QWidgetAction_createdWidgets, "QWidgetAction.createdWidgets() -> list-of-QWidget");

extern "C" {static PyObject *meth_QWidgetAction_createdWidgets(PyObject *, PyObject *);}
static PyObject *meth_QWidgetAction_createdWidgets(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const QWidgetAction *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "p", &sipSelf, sipType_QWidgetAction, &sipCpp))
        {
            QList<QWidget*>*sipRes;

            sipRes = new QList<QWidget*>(sipCpp->createdWidgets());

            return sipConvertFromNewType(sipRes,sipType_QList_0101QWidget,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QWidgetAction, sipName_createdWidgets, doc_QWidgetAction_createdWidgets);

    return NULL;
}


/* Cast a pointer to a type somewhere in its superclass hierarchy. */
extern "C" {static void *cast_QWidgetAction(void *, const sipTypeDef *);}
static void *cast_QWidgetAction(void *ptr, const sipTypeDef *targetType)
{
    void *res;

    if (targetType == sipType_QWidgetAction)
        return ptr;

    if ((res = ((const sipClassTypeDef *)sipType_QAction)->ctd_cast((QAction *)(QWidgetAction *)ptr,targetType)) != NULL)
        return res;

    return NULL;
}


/* Call the instance's destructor. */
extern "C" {static void release_QWidgetAction(void *, int);}
static void release_QWidgetAction(void *sipCppV,int)
{
    QWidgetAction *sipCpp = reinterpret_cast<QWidgetAction *>(sipCppV);

    if (QThread::currentThread() == sipCpp->thread())
        delete sipCpp;
    else
        sipCpp->deleteLater();
}


extern "C" {static void dealloc_QWidgetAction(sipSimpleWrapper *);}
static void dealloc_QWidgetAction(sipSimpleWrapper *sipSelf)
{
    if (sipIsDerived(sipSelf))
        reinterpret_cast<sipQWidgetAction *>(sipGetAddress(sipSelf))->sipPySelf = NULL;

    if (sipIsPyOwned(sipSelf))
    {
        release_QWidgetAction(sipGetAddress(sipSelf),sipSelf->flags);
    }
}


extern "C" {static void *init_type_QWidgetAction(sipSimpleWrapper *, PyObject *, PyObject *, PyObject **, PyObject **, PyObject **);}
static void *init_type_QWidgetAction(sipSimpleWrapper *sipSelf, PyObject *sipArgs, PyObject *sipKwds, PyObject **sipUnused, PyObject **sipOwner, PyObject **sipParseErr)
{
    sipQWidgetAction *sipCpp = 0;

    {
        QObject* a0;

        if (sipParseKwdArgs(sipParseErr, sipArgs, sipKwds, NULL, sipUnused, "JH", sipType_QObject, &a0, sipOwner))
        {
            sipCpp = new sipQWidgetAction(a0);

            sipCpp->sipPySelf = sipSelf;

            return sipCpp;
        }
    }

    return NULL;
}


/* Define this type's super-types. */
static sipEncodedTypeDef supers_QWidgetAction[] = {{25, 255, 1}};


static PyMethodDef methods_QWidgetAction[] = {
    {SIP_MLNAME_CAST(sipName_createWidget), meth_QWidgetAction_createWidget, METH_VARARGS, SIP_MLDOC_CAST(doc_QWidgetAction_createWidget)},
    {SIP_MLNAME_CAST(sipName_createdWidgets), meth_QWidgetAction_createdWidgets, METH_VARARGS, SIP_MLDOC_CAST(doc_QWidgetAction_createdWidgets)},
    {SIP_MLNAME_CAST(sipName_defaultWidget), meth_QWidgetAction_defaultWidget, METH_VARARGS, SIP_MLDOC_CAST(doc_QWidgetAction_defaultWidget)},
    {SIP_MLNAME_CAST(sipName_deleteWidget), meth_QWidgetAction_deleteWidget, METH_VARARGS, SIP_MLDOC_CAST(doc_QWidgetAction_deleteWidget)},
    {SIP_MLNAME_CAST(sipName_event), meth_QWidgetAction_event, METH_VARARGS, SIP_MLDOC_CAST(doc_QWidgetAction_event)},
    {SIP_MLNAME_CAST(sipName_eventFilter), meth_QWidgetAction_eventFilter, METH_VARARGS, SIP_MLDOC_CAST(doc_QWidgetAction_eventFilter)},
    {SIP_MLNAME_CAST(sipName_releaseWidget), meth_QWidgetAction_releaseWidget, METH_VARARGS, SIP_MLDOC_CAST(doc_QWidgetAction_releaseWidget)},
    {SIP_MLNAME_CAST(sipName_requestWidget), meth_QWidgetAction_requestWidget, METH_VARARGS, SIP_MLDOC_CAST(doc_QWidgetAction_requestWidget)},
    {SIP_MLNAME_CAST(sipName_setDefaultWidget), meth_QWidgetAction_setDefaultWidget, METH_VARARGS, SIP_MLDOC_CAST(doc_QWidgetAction_setDefaultWidget)}
};

PyDoc_STRVAR(doc_QWidgetAction, "\1QWidgetAction(QObject)");


pyqt5ClassTypeDef sipTypeDef_QtWidgets_QWidgetAction = {
{
    {
        -1,
        0,
        0,
        SIP_TYPE_SCC|SIP_TYPE_SUPER_INIT|SIP_TYPE_CLASS,
        sipNameNr_QWidgetAction,
        {0}
    },
    {
        sipNameNr_QWidgetAction,
        {0, 0, 1},
        9, methods_QWidgetAction,
        0, 0,
        0, 0,
        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    },
    doc_QWidgetAction,
    -1,
    -1,
    supers_QWidgetAction,
    0,
    init_type_QWidgetAction,
    0,
    0,
#if PY_MAJOR_VERSION >= 3
    0,
    0,
#else
    0,
    0,
    0,
    0,
#endif
    dealloc_QWidgetAction,
    0,
    0,
    0,
    release_QWidgetAction,
    cast_QWidgetAction,
    0,
    0,
    0,
    0,
    0,
    0
},
    &QWidgetAction::staticMetaObject,
    0,
    0,
    0
};
