/*
 * Interface wrapper code.
 *
 * Generated by SIP 4.16.6-snapshot-3c5425fa3c80 on Thu Jan 22 20:34:15 2015
 *
 * Copyright (c) 2014 Riverbank Computing Limited <info@riverbankcomputing.com>
 * 
 * This file is part of PyQt5.
 * 
 * This file may be used under the terms of the GNU General Public License
 * version 3.0 as published by the Free Software Foundation and appearing in
 * the file LICENSE included in the packaging of this file.  Please review the
 * following information to ensure the GNU General Public License version 3.0
 * requirements will be met: http://www.gnu.org/copyleft/gpl.html.
 * 
 * If you do not wish to use this file under the terms of the GPL version 3.0
 * then you may purchase a commercial license.  For more information contact
 * info@riverbankcomputing.com.
 * 
 * This file is provided AS IS with NO WARRANTY OF ANY KIND, INCLUDING THE
 * WARRANTY OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 */

#include "sipAPIQtHelp.h"

#line 46 "/home/supermap/OpenThings/pyqt5/sip/QtHelp/qhelpindexwidget.sip"
#include <qhelpindexwidget.h>
#line 29 "/home/supermap/OpenThings/pyqt5/QtHelp/sipQtHelpQHelpIndexWidget.cpp"

#line 27 "sip/QtCore/qstring.sip"
#include <qstring.h>
#line 33 "/home/supermap/OpenThings/pyqt5/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 26 "sip/QtCore/qpycore_qmap.sip"
#include <qmap.h>
#line 36 "/home/supermap/OpenThings/pyqt5/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 100 "sip/QtCore/qurl.sip"
#include <qurl.h>
#line 39 "/home/supermap/OpenThings/pyqt5/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 26 "sip/QtCore/qabstractitemmodel.sip"
#include <qabstractitemmodel.h>
#line 42 "/home/supermap/OpenThings/pyqt5/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 133 "sip/QtCore/qitemselectionmodel.sip"
#include <qitemselectionmodel.h>
#line 45 "/home/supermap/OpenThings/pyqt5/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 30 "sip/QtCore/qsize.sip"
#include <qsize.h>
#line 48 "/home/supermap/OpenThings/pyqt5/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 36 "sip/QtCore/qpycore_qlist.sip"
#include <qlist.h>
#line 51 "/home/supermap/OpenThings/pyqt5/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 30 "sip/QtGui/qregion.sip"
#include <qregion.h>
#line 54 "/home/supermap/OpenThings/pyqt5/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 30 "sip/QtCore/qrect.sip"
#include <qrect.h>
#line 57 "/home/supermap/OpenThings/pyqt5/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 68 "sip/QtCore/qitemselectionmodel.sip"
#include <qitemselectionmodel.h>
#line 60 "/home/supermap/OpenThings/pyqt5/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 30 "sip/QtCore/qpoint.sip"
#include <qpoint.h>
#line 63 "/home/supermap/OpenThings/pyqt5/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 30 "sip/QtWidgets/qabstractitemview.sip"
#include <qabstractitemview.h>
#line 66 "/home/supermap/OpenThings/pyqt5/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 30 "sip/QtCore/qnamespace.sip"
#include <qnamespace.h>
#line 69 "/home/supermap/OpenThings/pyqt5/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 368 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 72 "/home/supermap/OpenThings/pyqt5/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 564 "sip/QtWidgets/qstyleoption.sip"
#include <qstyleoption.h>
#line 75 "/home/supermap/OpenThings/pyqt5/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 30 "sip/QtCore/qnamespace.sip"
#include <qnamespace.h>
#line 78 "/home/supermap/OpenThings/pyqt5/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 534 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 81 "/home/supermap/OpenThings/pyqt5/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 583 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 84 "/home/supermap/OpenThings/pyqt5/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 556 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 87 "/home/supermap/OpenThings/pyqt5/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 395 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 90 "/home/supermap/OpenThings/pyqt5/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 222 "sip/QtCore/qcoreevent.sip"
#include <qcoreevent.h>
#line 93 "/home/supermap/OpenThings/pyqt5/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 202 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 96 "/home/supermap/OpenThings/pyqt5/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 26 "sip/QtCore/qcoreevent.sip"
#include <qcoreevent.h>
#line 99 "/home/supermap/OpenThings/pyqt5/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 321 "sip/QtCore/qpycore_qvector.sip"
#include <qvector.h>
#line 102 "/home/supermap/OpenThings/pyqt5/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 26 "sip/QtWidgets/qlistview.sip"
#include <qlistview.h>
#line 105 "/home/supermap/OpenThings/pyqt5/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 30 "sip/QtCore/qnamespace.sip"
#include <qnamespace.h>
#line 108 "/home/supermap/OpenThings/pyqt5/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 479 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 111 "/home/supermap/OpenThings/pyqt5/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 30 "sip/QtCore/qvariant.sip"
#include <qvariant.h>
#line 114 "/home/supermap/OpenThings/pyqt5/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 26 "sip/QtWidgets/qabstractitemdelegate.sip"
#include <qabstractitemdelegate.h>
#line 117 "/home/supermap/OpenThings/pyqt5/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 333 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 120 "/home/supermap/OpenThings/pyqt5/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 354 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 123 "/home/supermap/OpenThings/pyqt5/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 572 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 126 "/home/supermap/OpenThings/pyqt5/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 28 "sip/QtCore/qobject.sip"
#include <qobject.h>
#line 129 "/home/supermap/OpenThings/pyqt5/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 30 "sip/QtWidgets/qwidget.sip"
#include <qwidget.h>
#line 132 "/home/supermap/OpenThings/pyqt5/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 30 "sip/QtWidgets/qabstractitemview.sip"
#include <qabstractitemview.h>
#line 135 "/home/supermap/OpenThings/pyqt5/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 68 "sip/QtCore/qitemselectionmodel.sip"
#include <qitemselectionmodel.h>
#line 138 "/home/supermap/OpenThings/pyqt5/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 105 "sip/QtCore/qabstractitemmodel.sip"
#include <qabstractitemmodel.h>
#line 141 "/home/supermap/OpenThings/pyqt5/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 26 "sip/QtWidgets/qabstractscrollarea.sip"
#include <qabstractscrollarea.h>
#line 144 "/home/supermap/OpenThings/pyqt5/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 144 "sip/QtCore/qpycore_qlist.sip"
#include <qlist.h>
#line 147 "/home/supermap/OpenThings/pyqt5/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 30 "sip/QtCore/qnamespace.sip"
#include <qnamespace.h>
#line 150 "/home/supermap/OpenThings/pyqt5/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 26 "sip/QtWidgets/qscrollbar.sip"
#include <qscrollbar.h>
#line 153 "/home/supermap/OpenThings/pyqt5/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 452 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 156 "/home/supermap/OpenThings/pyqt5/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 247 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 159 "/home/supermap/OpenThings/pyqt5/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 30 "sip/QtCore/qmargins.sip"
#include <qmargins.h>
#line 162 "/home/supermap/OpenThings/pyqt5/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 30 "sip/QtGui/qpainter.sip"
#include <qpainter.h>
#line 165 "/home/supermap/OpenThings/pyqt5/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 26 "sip/QtWidgets/qframe.sip"
#include <qframe.h>
#line 168 "/home/supermap/OpenThings/pyqt5/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 30 "sip/QtGui/qicon.sip"
#include <qicon.h>
#line 171 "/home/supermap/OpenThings/pyqt5/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 32 "sip/QtCore/qbytearray.sip"
#include <qbytearray.h>
#line 174 "/home/supermap/OpenThings/pyqt5/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 26 "sip/QtGui/qwindow.sip"
#include <qwindow.h>
#line 177 "/home/supermap/OpenThings/pyqt5/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 30 "sip/QtCore/qnamespace.sip"
#include <qnamespace.h>
#line 180 "/home/supermap/OpenThings/pyqt5/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 30 "sip/QtGui/qpixmap.sip"
#include <qpixmap.h>
#line 183 "/home/supermap/OpenThings/pyqt5/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 30 "sip/QtCore/qnamespace.sip"
#include <qnamespace.h>
#line 186 "/home/supermap/OpenThings/pyqt5/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 30 "sip/QtCore/qnamespace.sip"
#include <qnamespace.h>
#line 189 "/home/supermap/OpenThings/pyqt5/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 30 "sip/QtWidgets/qgraphicseffect.sip"
#include <qgraphicseffect.h>
#line 192 "/home/supermap/OpenThings/pyqt5/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 26 "sip/QtWidgets/qgraphicsproxywidget.sip"
#include <qgraphicsproxywidget.h>
#line 195 "/home/supermap/OpenThings/pyqt5/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 192 "sip/QtCore/qglobal.sip"
#include <QtGlobal>
#line 198 "/home/supermap/OpenThings/pyqt5/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 30 "sip/QtCore/qlocale.sip"
#include <qlocale.h>
#line 201 "/home/supermap/OpenThings/pyqt5/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 26 "sip/QtGui/qpaintdevice.sip"
#include <qpaintdevice.h>
#line 204 "/home/supermap/OpenThings/pyqt5/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 30 "sip/QtWidgets/qwidget.sip"
#include <qwidget.h>
#line 207 "/home/supermap/OpenThings/pyqt5/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 26 "sip/QtGui/qfontinfo.sip"
#include <qfontinfo.h>
#line 210 "/home/supermap/OpenThings/pyqt5/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 26 "sip/QtGui/qfontmetrics.sip"
#include <qfontmetrics.h>
#line 213 "/home/supermap/OpenThings/pyqt5/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 30 "sip/QtGui/qfont.sip"
#include <qfont.h>
#line 216 "/home/supermap/OpenThings/pyqt5/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 441 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 219 "/home/supermap/OpenThings/pyqt5/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 430 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 222 "/home/supermap/OpenThings/pyqt5/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 635 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 225 "/home/supermap/OpenThings/pyqt5/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 275 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 228 "/home/supermap/OpenThings/pyqt5/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 408 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 231 "/home/supermap/OpenThings/pyqt5/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 382 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 234 "/home/supermap/OpenThings/pyqt5/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 56 "sip/QtGui/qpaintengine.sip"
#include <qpaintengine.h>
#line 237 "/home/supermap/OpenThings/pyqt5/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 144 "sip/QtCore/qpycore_qlist.sip"
#include <qlist.h>
#line 240 "/home/supermap/OpenThings/pyqt5/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 26 "sip/QtWidgets/qaction.sip"
#include <qaction.h>
#line 243 "/home/supermap/OpenThings/pyqt5/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 26 "sip/QtWidgets/qlayout.sip"
#include <qlayout.h>
#line 246 "/home/supermap/OpenThings/pyqt5/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 30 "sip/QtWidgets/qsizepolicy.sip"
#include <qsizepolicy.h>
#line 249 "/home/supermap/OpenThings/pyqt5/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 30 "sip/QtCore/qnamespace.sip"
#include <qnamespace.h>
#line 252 "/home/supermap/OpenThings/pyqt5/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 30 "sip/QtGui/qkeysequence.sip"
#include <qkeysequence.h>
#line 255 "/home/supermap/OpenThings/pyqt5/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 30 "sip/QtGui/qcursor.sip"
#include <qcursor.h>
#line 258 "/home/supermap/OpenThings/pyqt5/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 26 "sip/QtGui/qbitmap.sip"
#include <qbitmap.h>
#line 261 "/home/supermap/OpenThings/pyqt5/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 30 "sip/QtGui/qpalette.sip"
#include <qpalette.h>
#line 264 "/home/supermap/OpenThings/pyqt5/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 30 "sip/QtWidgets/qstyle.sip"
#include <qstyle.h>
#line 267 "/home/supermap/OpenThings/pyqt5/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 30 "sip/QtCore/qmetaobject.sip"
#include <qmetaobject.h>
#line 270 "/home/supermap/OpenThings/pyqt5/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 234 "sip/QtCore/qcoreevent.sip"
#include <qcoreevent.h>
#line 273 "/home/supermap/OpenThings/pyqt5/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 36 "sip/QtCore/qpycore_qlist.sip"
#include <qlist.h>
#line 276 "/home/supermap/OpenThings/pyqt5/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 144 "sip/QtCore/qpycore_qlist.sip"
#include <qlist.h>
#line 279 "/home/supermap/OpenThings/pyqt5/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 26 "sip/QtCore/qthread.sip"
#include <qthread.h>
#line 282 "/home/supermap/OpenThings/pyqt5/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 30 "sip/QtCore/qnamespace.sip"
#include <qnamespace.h>
#line 285 "/home/supermap/OpenThings/pyqt5/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 30 "sip/QtCore/qregexp.sip"
#include <qregexp.h>
#line 288 "/home/supermap/OpenThings/pyqt5/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 30 "sip/QtCore/qregularexpression.sip"
#include <qregularexpression.h>
#line 291 "/home/supermap/OpenThings/pyqt5/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 26 "sip/QtCore/qobjectdefs.sip"
#include <qobjectdefs.h>
#line 294 "/home/supermap/OpenThings/pyqt5/QtHelp/sipQtHelpQHelpIndexWidget.cpp"


PyDoc_STRVAR(doc_QHelpIndexWidget_filterIndices, "QHelpIndexWidget.filterIndices(str, str wildcard='')");

extern "C" {static PyObject *meth_QHelpIndexWidget_filterIndices(PyObject *, PyObject *, PyObject *);}
static PyObject *meth_QHelpIndexWidget_filterIndices(PyObject *sipSelf, PyObject *sipArgs, PyObject *sipKwds)
{
    PyObject *sipParseErr = NULL;

    {
        const QString* a0;
        int a0State = 0;
        const QString& a1def = QString();
        const QString* a1 = &a1def;
        int a1State = 0;
        QHelpIndexWidget *sipCpp;

        static const char *sipKwdList[] = {
            NULL,
            sipName_wildcard,
        };

        if (sipParseKwdArgs(&sipParseErr, sipArgs, sipKwds, sipKwdList, NULL, "BJ1|J1", &sipSelf, sipType_QHelpIndexWidget, &sipCpp, sipType_QString,&a0, &a0State, sipType_QString,&a1, &a1State))
        {
            sipCpp->filterIndices(*a0,*a1);
            sipReleaseType(const_cast<QString *>(a0),sipType_QString,a0State);
            sipReleaseType(const_cast<QString *>(a1),sipType_QString,a1State);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QHelpIndexWidget, sipName_filterIndices, doc_QHelpIndexWidget_filterIndices);

    return NULL;
}


PyDoc_STRVAR(doc_QHelpIndexWidget_activateCurrentItem, "QHelpIndexWidget.activateCurrentItem()");

extern "C" {static PyObject *meth_QHelpIndexWidget_activateCurrentItem(PyObject *, PyObject *);}
static PyObject *meth_QHelpIndexWidget_activateCurrentItem(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        QHelpIndexWidget *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QHelpIndexWidget, &sipCpp))
        {
            sipCpp->activateCurrentItem();

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QHelpIndexWidget, sipName_activateCurrentItem, doc_QHelpIndexWidget_activateCurrentItem);

    return NULL;
}


/* Cast a pointer to a type somewhere in its superclass hierarchy. */
extern "C" {static void *cast_QHelpIndexWidget(void *, const sipTypeDef *);}
static void *cast_QHelpIndexWidget(void *ptr, const sipTypeDef *targetType)
{
    void *res;

    if (targetType == sipType_QHelpIndexWidget)
        return ptr;

    if ((res = ((const sipClassTypeDef *)sipType_QListView)->ctd_cast((QListView *)(QHelpIndexWidget *)ptr,targetType)) != NULL)
        return res;

    return NULL;
}


/* Call the instance's destructor. */
extern "C" {static void release_QHelpIndexWidget(void *, int);}
static void release_QHelpIndexWidget(void *sipCppV,int)
{
    QHelpIndexWidget *sipCpp = reinterpret_cast<QHelpIndexWidget *>(sipCppV);

    if (QThread::currentThread() == sipCpp->thread())
        delete sipCpp;
    else
        sipCpp->deleteLater();
}


extern "C" {static void dealloc_QHelpIndexWidget(sipSimpleWrapper *);}
static void dealloc_QHelpIndexWidget(sipSimpleWrapper *sipSelf)
{
    if (sipIsPyOwned(sipSelf))
    {
        release_QHelpIndexWidget(sipGetAddress(sipSelf),0);
    }
}


/* Define this type's super-types. */
static sipEncodedTypeDef supers_QHelpIndexWidget[] = {{211, 2, 1}};


static PyMethodDef methods_QHelpIndexWidget[] = {
    {SIP_MLNAME_CAST(sipName_activateCurrentItem), meth_QHelpIndexWidget_activateCurrentItem, METH_VARARGS, SIP_MLDOC_CAST(doc_QHelpIndexWidget_activateCurrentItem)},
    {SIP_MLNAME_CAST(sipName_filterIndices), (PyCFunction)meth_QHelpIndexWidget_filterIndices, METH_VARARGS|METH_KEYWORDS, SIP_MLDOC_CAST(doc_QHelpIndexWidget_filterIndices)}
};


/* Define this type's signals. */
static const pyqt5QtSignal signals_QHelpIndexWidget[] = {
    {"linksActivated(QMap<QString,QUrl>,QString)", "\1QHelpIndexWidget.linksActivated[dict-of-QString-QUrl, str]", 0, 0},
    {"linkActivated(QUrl,QString)", "\1QHelpIndexWidget.linkActivated[QUrl, str]", 0, 0},
    {0, 0, 0, 0}
};


pyqt5ClassTypeDef sipTypeDef_QtHelp_QHelpIndexWidget = {
{
    {
        -1,
        0,
        0,
        SIP_TYPE_SCC|SIP_TYPE_SUPER_INIT|SIP_TYPE_CLASS,
        sipNameNr_QHelpIndexWidget,
        {0}
    },
    {
        sipNameNr_QHelpIndexWidget,
        {0, 0, 1},
        2, methods_QHelpIndexWidget,
        0, 0,
        0, 0,
        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    },
    0,
    -1,
    -1,
    supers_QHelpIndexWidget,
    0,
    0,
    0,
    0,
#if PY_MAJOR_VERSION >= 3
    0,
    0,
#else
    0,
    0,
    0,
    0,
#endif
    dealloc_QHelpIndexWidget,
    0,
    0,
    0,
    release_QHelpIndexWidget,
    cast_QHelpIndexWidget,
    0,
    0,
    0,
    0,
    0,
    0
},
    &QHelpIndexWidget::staticMetaObject,
    0,
    signals_QHelpIndexWidget,
    0
};
