/*
 * Interface wrapper code.
 *
 * Generated by SIP 4.16.6-snapshot-3c5425fa3c80 on Thu Jan 22 20:35:36 2015
 *
 * Copyright (c) 2014 Riverbank Computing Limited <info@riverbankcomputing.com>
 * 
 * This file is part of PyQt5.
 * 
 * This file may be used under the terms of the GNU General Public License
 * version 3.0 as published by the Free Software Foundation and appearing in
 * the file LICENSE included in the packaging of this file.  Please review the
 * following information to ensure the GNU General Public License version 3.0
 * requirements will be met: http://www.gnu.org/copyleft/gpl.html.
 * 
 * If you do not wish to use this file under the terms of the GPL version 3.0
 * then you may purchase a commercial license.  For more information contact
 * info@riverbankcomputing.com.
 * 
 * This file is provided AS IS with NO WARRANTY OF ANY KIND, INCLUDING THE
 * WARRANTY OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 */

#include "sipAPIQtDesigner.h"

#line 26 "/home/supermap/OpenThings/pyqt5/sip/QtDesigner/abstractwidgetbox.sip"
#include <abstractwidgetbox.h>
#line 29 "/home/supermap/OpenThings/pyqt5/QtDesigner/sipQtDesignerQDesignerWidgetBoxInterface.cpp"

#line 30 "sip/QtWidgets/qwidget.sip"
#include <qwidget.h>
#line 33 "/home/supermap/OpenThings/pyqt5/QtDesigner/sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 30 "sip/QtCore/qnamespace.sip"
#include <qnamespace.h>
#line 36 "/home/supermap/OpenThings/pyqt5/QtDesigner/sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 27 "sip/QtCore/qstring.sip"
#include <qstring.h>
#line 39 "/home/supermap/OpenThings/pyqt5/QtDesigner/sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 30 "sip/QtGui/qicon.sip"
#include <qicon.h>
#line 42 "/home/supermap/OpenThings/pyqt5/QtDesigner/sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 30 "sip/QtGui/qpainter.sip"
#include <qpainter.h>
#line 45 "/home/supermap/OpenThings/pyqt5/QtDesigner/sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 32 "sip/QtCore/qbytearray.sip"
#include <qbytearray.h>
#line 48 "/home/supermap/OpenThings/pyqt5/QtDesigner/sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 26 "sip/QtGui/qwindow.sip"
#include <qwindow.h>
#line 51 "/home/supermap/OpenThings/pyqt5/QtDesigner/sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 30 "sip/QtGui/qpixmap.sip"
#include <qpixmap.h>
#line 54 "/home/supermap/OpenThings/pyqt5/QtDesigner/sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 30 "sip/QtCore/qrect.sip"
#include <qrect.h>
#line 57 "/home/supermap/OpenThings/pyqt5/QtDesigner/sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 30 "sip/QtCore/qnamespace.sip"
#include <qnamespace.h>
#line 60 "/home/supermap/OpenThings/pyqt5/QtDesigner/sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 30 "sip/QtCore/qmargins.sip"
#include <qmargins.h>
#line 63 "/home/supermap/OpenThings/pyqt5/QtDesigner/sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 30 "sip/QtCore/qnamespace.sip"
#include <qnamespace.h>
#line 66 "/home/supermap/OpenThings/pyqt5/QtDesigner/sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 30 "sip/QtCore/qnamespace.sip"
#include <qnamespace.h>
#line 69 "/home/supermap/OpenThings/pyqt5/QtDesigner/sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 30 "sip/QtWidgets/qgraphicseffect.sip"
#include <qgraphicseffect.h>
#line 72 "/home/supermap/OpenThings/pyqt5/QtDesigner/sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 26 "sip/QtWidgets/qgraphicsproxywidget.sip"
#include <qgraphicsproxywidget.h>
#line 75 "/home/supermap/OpenThings/pyqt5/QtDesigner/sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 192 "sip/QtCore/qglobal.sip"
#include <QtGlobal>
#line 78 "/home/supermap/OpenThings/pyqt5/QtDesigner/sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 30 "sip/QtCore/qlocale.sip"
#include <qlocale.h>
#line 81 "/home/supermap/OpenThings/pyqt5/QtDesigner/sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 26 "sip/QtGui/qpaintdevice.sip"
#include <qpaintdevice.h>
#line 84 "/home/supermap/OpenThings/pyqt5/QtDesigner/sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 30 "sip/QtCore/qpoint.sip"
#include <qpoint.h>
#line 87 "/home/supermap/OpenThings/pyqt5/QtDesigner/sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 30 "sip/QtGui/qregion.sip"
#include <qregion.h>
#line 90 "/home/supermap/OpenThings/pyqt5/QtDesigner/sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 30 "sip/QtWidgets/qwidget.sip"
#include <qwidget.h>
#line 93 "/home/supermap/OpenThings/pyqt5/QtDesigner/sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 30 "sip/QtCore/qsize.sip"
#include <qsize.h>
#line 96 "/home/supermap/OpenThings/pyqt5/QtDesigner/sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 26 "sip/QtGui/qfontinfo.sip"
#include <qfontinfo.h>
#line 99 "/home/supermap/OpenThings/pyqt5/QtDesigner/sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 26 "sip/QtGui/qfontmetrics.sip"
#include <qfontmetrics.h>
#line 102 "/home/supermap/OpenThings/pyqt5/QtDesigner/sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 30 "sip/QtGui/qfont.sip"
#include <qfont.h>
#line 105 "/home/supermap/OpenThings/pyqt5/QtDesigner/sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 30 "sip/QtCore/qvariant.sip"
#include <qvariant.h>
#line 108 "/home/supermap/OpenThings/pyqt5/QtDesigner/sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 479 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 111 "/home/supermap/OpenThings/pyqt5/QtDesigner/sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 26 "sip/QtCore/qcoreevent.sip"
#include <qcoreevent.h>
#line 114 "/home/supermap/OpenThings/pyqt5/QtDesigner/sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 441 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 117 "/home/supermap/OpenThings/pyqt5/QtDesigner/sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 430 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 120 "/home/supermap/OpenThings/pyqt5/QtDesigner/sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 534 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 123 "/home/supermap/OpenThings/pyqt5/QtDesigner/sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 583 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 126 "/home/supermap/OpenThings/pyqt5/QtDesigner/sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 556 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 129 "/home/supermap/OpenThings/pyqt5/QtDesigner/sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 572 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 132 "/home/supermap/OpenThings/pyqt5/QtDesigner/sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 635 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 135 "/home/supermap/OpenThings/pyqt5/QtDesigner/sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 275 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 138 "/home/supermap/OpenThings/pyqt5/QtDesigner/sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 452 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 141 "/home/supermap/OpenThings/pyqt5/QtDesigner/sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 408 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 144 "/home/supermap/OpenThings/pyqt5/QtDesigner/sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 395 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 147 "/home/supermap/OpenThings/pyqt5/QtDesigner/sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 382 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 150 "/home/supermap/OpenThings/pyqt5/QtDesigner/sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 368 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 153 "/home/supermap/OpenThings/pyqt5/QtDesigner/sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 354 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 156 "/home/supermap/OpenThings/pyqt5/QtDesigner/sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 333 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 159 "/home/supermap/OpenThings/pyqt5/QtDesigner/sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 247 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 162 "/home/supermap/OpenThings/pyqt5/QtDesigner/sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 202 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 165 "/home/supermap/OpenThings/pyqt5/QtDesigner/sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 56 "sip/QtGui/qpaintengine.sip"
#include <qpaintengine.h>
#line 168 "/home/supermap/OpenThings/pyqt5/QtDesigner/sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 144 "sip/QtCore/qpycore_qlist.sip"
#include <qlist.h>
#line 171 "/home/supermap/OpenThings/pyqt5/QtDesigner/sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 26 "sip/QtWidgets/qaction.sip"
#include <qaction.h>
#line 174 "/home/supermap/OpenThings/pyqt5/QtDesigner/sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 26 "sip/QtWidgets/qlayout.sip"
#include <qlayout.h>
#line 177 "/home/supermap/OpenThings/pyqt5/QtDesigner/sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 30 "sip/QtWidgets/qsizepolicy.sip"
#include <qsizepolicy.h>
#line 180 "/home/supermap/OpenThings/pyqt5/QtDesigner/sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 30 "sip/QtCore/qnamespace.sip"
#include <qnamespace.h>
#line 183 "/home/supermap/OpenThings/pyqt5/QtDesigner/sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 30 "sip/QtGui/qkeysequence.sip"
#include <qkeysequence.h>
#line 186 "/home/supermap/OpenThings/pyqt5/QtDesigner/sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 30 "sip/QtGui/qcursor.sip"
#include <qcursor.h>
#line 189 "/home/supermap/OpenThings/pyqt5/QtDesigner/sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 26 "sip/QtGui/qbitmap.sip"
#include <qbitmap.h>
#line 192 "/home/supermap/OpenThings/pyqt5/QtDesigner/sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 30 "sip/QtGui/qpalette.sip"
#include <qpalette.h>
#line 195 "/home/supermap/OpenThings/pyqt5/QtDesigner/sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 30 "sip/QtWidgets/qstyle.sip"
#include <qstyle.h>
#line 198 "/home/supermap/OpenThings/pyqt5/QtDesigner/sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 30 "sip/QtCore/qmetaobject.sip"
#include <qmetaobject.h>
#line 201 "/home/supermap/OpenThings/pyqt5/QtDesigner/sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 234 "sip/QtCore/qcoreevent.sip"
#include <qcoreevent.h>
#line 204 "/home/supermap/OpenThings/pyqt5/QtDesigner/sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 222 "sip/QtCore/qcoreevent.sip"
#include <qcoreevent.h>
#line 207 "/home/supermap/OpenThings/pyqt5/QtDesigner/sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 28 "sip/QtCore/qobject.sip"
#include <qobject.h>
#line 210 "/home/supermap/OpenThings/pyqt5/QtDesigner/sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 36 "sip/QtCore/qpycore_qlist.sip"
#include <qlist.h>
#line 213 "/home/supermap/OpenThings/pyqt5/QtDesigner/sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 144 "sip/QtCore/qpycore_qlist.sip"
#include <qlist.h>
#line 216 "/home/supermap/OpenThings/pyqt5/QtDesigner/sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 26 "sip/QtCore/qthread.sip"
#include <qthread.h>
#line 219 "/home/supermap/OpenThings/pyqt5/QtDesigner/sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 30 "sip/QtCore/qnamespace.sip"
#include <qnamespace.h>
#line 222 "/home/supermap/OpenThings/pyqt5/QtDesigner/sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 30 "sip/QtCore/qregexp.sip"
#include <qregexp.h>
#line 225 "/home/supermap/OpenThings/pyqt5/QtDesigner/sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 30 "sip/QtCore/qregularexpression.sip"
#include <qregularexpression.h>
#line 228 "/home/supermap/OpenThings/pyqt5/QtDesigner/sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 26 "sip/QtCore/qobjectdefs.sip"
#include <qobjectdefs.h>
#line 231 "/home/supermap/OpenThings/pyqt5/QtDesigner/sipQtDesignerQDesignerWidgetBoxInterface.cpp"


PyDoc_STRVAR(doc_QDesignerWidgetBoxInterface_setFileName, "QDesignerWidgetBoxInterface.setFileName(str)");

extern "C" {static PyObject *meth_QDesignerWidgetBoxInterface_setFileName(PyObject *, PyObject *);}
static PyObject *meth_QDesignerWidgetBoxInterface_setFileName(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    PyObject *sipOrigSelf = sipSelf;

    {
        const QString* a0;
        int a0State = 0;
        QDesignerWidgetBoxInterface *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ1", &sipSelf, sipType_QDesignerWidgetBoxInterface, &sipCpp, sipType_QString,&a0, &a0State))
        {
            if (!sipOrigSelf)
            {
                sipAbstractMethod(sipName_QDesignerWidgetBoxInterface, sipName_setFileName);
                return NULL;
            }

            sipCpp->setFileName(*a0);
            sipReleaseType(const_cast<QString *>(a0),sipType_QString,a0State);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QDesignerWidgetBoxInterface, sipName_setFileName, doc_QDesignerWidgetBoxInterface_setFileName);

    return NULL;
}


PyDoc_STRVAR(doc_QDesignerWidgetBoxInterface_fileName, "QDesignerWidgetBoxInterface.fileName() -> str");

extern "C" {static PyObject *meth_QDesignerWidgetBoxInterface_fileName(PyObject *, PyObject *);}
static PyObject *meth_QDesignerWidgetBoxInterface_fileName(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    PyObject *sipOrigSelf = sipSelf;

    {
        const QDesignerWidgetBoxInterface *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QDesignerWidgetBoxInterface, &sipCpp))
        {
            QString*sipRes;

            if (!sipOrigSelf)
            {
                sipAbstractMethod(sipName_QDesignerWidgetBoxInterface, sipName_fileName);
                return NULL;
            }

            sipRes = new QString(sipCpp->fileName());

            return sipConvertFromNewType(sipRes,sipType_QString,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QDesignerWidgetBoxInterface, sipName_fileName, doc_QDesignerWidgetBoxInterface_fileName);

    return NULL;
}


PyDoc_STRVAR(doc_QDesignerWidgetBoxInterface_load, "QDesignerWidgetBoxInterface.load() -> bool");

extern "C" {static PyObject *meth_QDesignerWidgetBoxInterface_load(PyObject *, PyObject *);}
static PyObject *meth_QDesignerWidgetBoxInterface_load(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    PyObject *sipOrigSelf = sipSelf;

    {
        QDesignerWidgetBoxInterface *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QDesignerWidgetBoxInterface, &sipCpp))
        {
            bool sipRes;

            if (!sipOrigSelf)
            {
                sipAbstractMethod(sipName_QDesignerWidgetBoxInterface, sipName_load);
                return NULL;
            }

            sipRes = sipCpp->load();

            return PyBool_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QDesignerWidgetBoxInterface, sipName_load, doc_QDesignerWidgetBoxInterface_load);

    return NULL;
}


PyDoc_STRVAR(doc_QDesignerWidgetBoxInterface_save, "QDesignerWidgetBoxInterface.save() -> bool");

extern "C" {static PyObject *meth_QDesignerWidgetBoxInterface_save(PyObject *, PyObject *);}
static PyObject *meth_QDesignerWidgetBoxInterface_save(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    PyObject *sipOrigSelf = sipSelf;

    {
        QDesignerWidgetBoxInterface *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QDesignerWidgetBoxInterface, &sipCpp))
        {
            bool sipRes;

            if (!sipOrigSelf)
            {
                sipAbstractMethod(sipName_QDesignerWidgetBoxInterface, sipName_save);
                return NULL;
            }

            sipRes = sipCpp->save();

            return PyBool_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QDesignerWidgetBoxInterface, sipName_save, doc_QDesignerWidgetBoxInterface_save);

    return NULL;
}


/* Cast a pointer to a type somewhere in its superclass hierarchy. */
extern "C" {static void *cast_QDesignerWidgetBoxInterface(void *, const sipTypeDef *);}
static void *cast_QDesignerWidgetBoxInterface(void *ptr, const sipTypeDef *targetType)
{
    void *res;

    if (targetType == sipType_QDesignerWidgetBoxInterface)
        return ptr;

    if ((res = ((const sipClassTypeDef *)sipType_QWidget)->ctd_cast((QWidget *)(QDesignerWidgetBoxInterface *)ptr,targetType)) != NULL)
        return res;

    return NULL;
}


/* Call the instance's destructor. */
extern "C" {static void release_QDesignerWidgetBoxInterface(void *, int);}
static void release_QDesignerWidgetBoxInterface(void *sipCppV,int)
{
    QDesignerWidgetBoxInterface *sipCpp = reinterpret_cast<QDesignerWidgetBoxInterface *>(sipCppV);

    if (QThread::currentThread() == sipCpp->thread())
        delete sipCpp;
    else
        sipCpp->deleteLater();
}


extern "C" {static void dealloc_QDesignerWidgetBoxInterface(sipSimpleWrapper *);}
static void dealloc_QDesignerWidgetBoxInterface(sipSimpleWrapper *sipSelf)
{
    if (sipIsPyOwned(sipSelf))
    {
        release_QDesignerWidgetBoxInterface(sipGetAddress(sipSelf),0);
    }
}


/* Define this type's super-types. */
static sipEncodedTypeDef supers_QDesignerWidgetBoxInterface[] = {{454, 2, 1}};


static PyMethodDef methods_QDesignerWidgetBoxInterface[] = {
    {SIP_MLNAME_CAST(sipName_fileName), meth_QDesignerWidgetBoxInterface_fileName, METH_VARARGS, SIP_MLDOC_CAST(doc_QDesignerWidgetBoxInterface_fileName)},
    {SIP_MLNAME_CAST(sipName_load), meth_QDesignerWidgetBoxInterface_load, METH_VARARGS, SIP_MLDOC_CAST(doc_QDesignerWidgetBoxInterface_load)},
    {SIP_MLNAME_CAST(sipName_save), meth_QDesignerWidgetBoxInterface_save, METH_VARARGS, SIP_MLDOC_CAST(doc_QDesignerWidgetBoxInterface_save)},
    {SIP_MLNAME_CAST(sipName_setFileName), meth_QDesignerWidgetBoxInterface_setFileName, METH_VARARGS, SIP_MLDOC_CAST(doc_QDesignerWidgetBoxInterface_setFileName)}
};


pyqt5ClassTypeDef sipTypeDef_QtDesigner_QDesignerWidgetBoxInterface = {
{
    {
        -1,
        0,
        0,
        SIP_TYPE_ABSTRACT|SIP_TYPE_SCC|SIP_TYPE_SUPER_INIT|SIP_TYPE_CLASS,
        sipNameNr_QDesignerWidgetBoxInterface,
        {0}
    },
    {
        sipNameNr_QDesignerWidgetBoxInterface,
        {0, 0, 1},
        4, methods_QDesignerWidgetBoxInterface,
        0, 0,
        0, 0,
        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    },
    0,
    -1,
    -1,
    supers_QDesignerWidgetBoxInterface,
    0,
    0,
    0,
    0,
#if PY_MAJOR_VERSION >= 3
    0,
    0,
#else
    0,
    0,
    0,
    0,
#endif
    dealloc_QDesignerWidgetBoxInterface,
    0,
    0,
    0,
    release_QDesignerWidgetBoxInterface,
    cast_QDesignerWidgetBoxInterface,
    0,
    0,
    0,
    0,
    0,
    0
},
    &QDesignerWidgetBoxInterface::staticMetaObject,
    0,
    0,
    0
};
